CREATE VIEW wymiary_konta AS
 SELECT i.ktn_idkonta AS idkontawymiaru,
    i.kt_idkonta AS idkonta_wymiaru,
    i.kt_fullnumer AS numerkonta_wymiaru,
    i.kt_nr_count AS numerkonta_wymiaru_pcount,
    i.kt_nr_p1 AS numerkonta_wymiaru_p1,
    i.kt_nr_p2 AS numerkonta_wymiaru_p2,
    i.kt_nr_p3 AS numerkonta_wymiaru_p3,
    i.kt_nr_p4 AS numerkonta_wymiaru_p4,
    i.kt_nr_p5 AS numerkonta_wymiaru_p5,
    i.kt_nr_p6 AS numerkonta_wymiaru_p6,
    i.kt_nr_p7 AS numerkonta_wymiaru_p7,
    i.kt_nr_p8 AS numerkonta_wymiaru_p8,
    i.kt_opis AS opiskonta_wymiaru,
    i.kt_nr_pfx1,
    i.kt_opis_pfx1,
    i.kt_nr_pfx2,
    i.kt_opis_pfx2,
    i.kt_nr_pfx3,
    i.kt_opis_pfx3,
    i.kt_nr_pfx4,
    i.kt_opis_pfx4,
    i.kt_nr_pfx5,
    i.kt_opis_pfx5,
    i.kt_nr_pfx6,
    i.kt_opis_pfx6,
    i.kt_nr_pfx7,
    i.kt_opis_pfx7,
    i.kt_nr_pfx8,
    i.kt_opis_pfx8,
    i.idcentrali
   FROM qvi.konta i;
