CREATE VIEW raport_zlecenia AS
 SELECT tg_zlecenia.zl_idzlecenia AS id,
    date(tg_zlecenia.zl_datazlecenia) AS data_przyjecia_zlecenia,
    date_part('year'::text, tg_zlecenia.zl_datazlecenia) AS rok_przyjecia_zlecenia,
    date_part('month'::text, tg_zlecenia.zl_datazlecenia) AS miesiac_przyjecia_zlecenia,
    date_part('week'::text, tg_zlecenia.zl_datazlecenia) AS tydzien_przyjecia_zlecenia,
    date_part('day'::text, tg_zlecenia.zl_datazlecenia) AS dzien_przyjecia_zlecenia,
    tg_zlecenia.zl_datazamkniecia AS data_zamkniecia_zlecenia,
    date_part('year'::text, tg_zlecenia.zl_datazamkniecia) AS rok_zamkniecia_zlecenia,
    date_part('month'::text, tg_zlecenia.zl_datazamkniecia) AS miesiac_zamkniecia_zlecenia,
    date_part('week'::text, tg_zlecenia.zl_datazamkniecia) AS tydzien_zamkniecia_zlecenia,
    date_part('day'::text, tg_zlecenia.zl_datazamkniecia) AS dzien_zamkniecia_zlecenia,
    date(tg_zlecenia.zl_datarozpoczecia) AS data_rozpoczecia_zlecenia,
    date_part('year'::text, tg_zlecenia.zl_datarozpoczecia) AS rok_rozpoczecia_zlec,
    date_part('month'::text, tg_zlecenia.zl_datarozpoczecia) AS miesiac_rozpoczecia_zlec,
    date_part('week'::text, tg_zlecenia.zl_datarozpoczecia) AS tydzien_rozpoczecia_zlec,
    date_part('day'::text, tg_zlecenia.zl_datarozpoczecia) AS dzien_rozpoczecia_zlec,
    date(tg_zlecenia.zl_datazakonczenia) AS data_zakonczenia_zlecenia,
    date_part('year'::text, tg_zlecenia.zl_datazakonczenia) AS rok_zakonczenia_zlecenia,
    date_part('month'::text, tg_zlecenia.zl_datazakonczenia) AS miesiac_zakonczenia_zlecenia,
    date_part('week'::text, tg_zlecenia.zl_datazakonczenia) AS tydzien_zakonczenia_zlecenia,
    date_part('day'::text, tg_zlecenia.zl_datazakonczenia) AS dzien_zakonczenia_zlecenia,
    (((date_part('year'::text, tg_zlecenia.zl_datazlecenia))::text || '.'::text) || uzupelnijmiesiac((date_part('month'::text, tg_zlecenia.zl_datazlecenia))::text)) AS rok_miesiac_przyjecia_zlecenia,
    (((date_part('year'::text, tg_zlecenia.zl_datazamkniecia))::text || '.'::text) || uzupelnijmiesiac((date_part('month'::text, tg_zlecenia.zl_datazamkniecia))::text)) AS rok_miesiac_zamkniecia_zlecenia,
    (((date_part('year'::text, tg_zlecenia.zl_datarozpoczecia))::text || '.'::text) || uzupelnijmiesiac((date_part('month'::text, tg_zlecenia.zl_datarozpoczecia))::text)) AS rok_miesiac_rozpoczecia_zlec,
    (((date_part('year'::text, tg_zlecenia.zl_datazakonczenia))::text || '.'::text) || uzupelnijmiesiac((date_part('month'::text, tg_zlecenia.zl_datazakonczenia))::text)) AS rok_miesiac_zakonczenia_zlec,
    ("substring"(((((((tg_zlecenia.zl_nrzlecenia)::text || '/'::text) || btrim((tg_zlecenia.zl_seria)::text)) || '/'::text) || (tg_zlecenia.zl_rok)::text) || '/ZLP'::text), 0, 50))::character varying(50) AS numer_zlecenia,
    ("substring"(btrim((tg_zlecenia.zl_seria)::text), 0, 8))::character varying(8) AS seria,
    ("substring"(tg_zlecenia.zl_nazwa, 0, 50))::character varying(50) AS kod_zlecenia,
    tg_zlecenia.zl_typ AS rodzajzlecenia,
    n.k_kod AS kododbiorcy_zlecenia,
    n.k_nazwa AS nazwaodbiorcy_zlecenia,
    n.rj_nazwa AS rejonodbiorcy_zlecenia,
    o.k_kod AS kodzlecajacego_zlecenia,
    o.k_nazwa AS nazwazlecajacego_zlecenia,
    o.rj_nazwa AS rejonzlecajacego_zlecenia,
    p.p_login AS odpowiedzialny,
    tg_zlecenia.zl_nazwa AS kod_imprezy,
    tg_zlecenia.zl_nazwisko_kod AS kontakt,
    tg_zlecenia.zl_telefon_cel AS kon_obcy,
    tg_zlecenia.zl_opis AS opis,
    statuszlecenia(((tg_zlecenia.zl_status & 14) >> 1)) AS status,
    ts_imprezy.ti_nazwa AS rodzaj_imprezy,
    ts_powiaty.pw_nazwa AS kraj,
    ts_powiaty.pw_wojewodztwo AS symbol_kraju,
    tg_zlecenia.zl_opiswykonania AS opis_wykonania,
    tg_zlecenia.zl_czaspracy AS ilosc_miejsc,
    tg_zlecenia.zl_liczbaosob AS liczba_zapisanych_osob,
    tg_zlecenia.zl_koszt AS koszt_netto,
    tg_zlecenia.zl_sumawplat AS wplaty,
    tg_zlecenia.zl_wrtbrutto AS przychody_brutto,
    tg_zlecenia.zl_wrtnetto AS przychody_netto,
    tg_zlecenia.zl_rozchodrw AS rozchod_rw,
    tg_zlecenia.zl_wydanie AS wydanie_magazyn,
    tg_zlecenia.zl_przychod AS przychod_magazyn,
    tg_zlecenia.zl_zwrot AS zwroty_produkcji,
    tg_zlecenia.zl_planprzychod AS plan_netto,
    tg_zlecenia.zl_planprzychodbrt AS plan_brutto,
    tg_zlecenia.zl_kosztbrt AS koszt_brutto,
    tg_zlecenia.zl_kosztfv AS koszty_dokumentu_handlowego,
    tg_zlecenia.zl_wyplaty AS wyplaty,
    etap.szl_opis AS aktualny_etap,
    (tg_zlecenia.zl_wrtnetto - tg_zlecenia.zl_koszt) AS marza,
    (policzwspolczynnik((tg_zlecenia.zl_wrtnetto - tg_zlecenia.zl_koszt), tg_zlecenia.zl_wrtnetto) * (100)::numeric) AS marzapr,
    imprazagrupowa(tg_zlecenia.zl_czaspracy) AS grup_ind,
    sprzedane(tg_zlecenia.zl_wrtnetto) AS sprzedana,
    seria2_jp((tg_zlecenia.zl_seria)::text) AS seria2
   FROM ((((((tg_zlecenia
     LEFT JOIN ( SELECT ts_statuszlecenia.szl_opis,
            tg_etapyzlecen.zl_idzlecenia
           FROM (ts_statuszlecenia
             JOIN tg_etapyzlecen USING (szl_idstatusu))) etap USING (zl_idzlecenia))
     LEFT JOIN ts_powiaty USING (pw_idpowiatu))
     LEFT JOIN ts_imprezy ON ((tg_zlecenia.zl_rodzajimp = ts_imprezy.ti_idimprezy)))
     LEFT JOIN ( SELECT tb_pracownicy.p_idpracownika,
            tb_pracownicy.p_login
           FROM tb_pracownicy) p ON ((tg_zlecenia.p_odpowiedzialny = p.p_idpracownika)))
     LEFT JOIN ( SELECT tb_klient.k_idklienta,
            tb_klient.k_kod,
            tb_klient.k_nazwa,
            ts_regiony.rj_nazwa,
            tb_klient.rk_idrodzajklienta
           FROM (tb_klient
             LEFT JOIN ts_regiony USING (rj_idregionu))) n ON ((tg_zlecenia.k_idklienta = n.k_idklienta)))
     LEFT JOIN ( SELECT tb_klient.k_idklienta,
            tb_klient.k_kod,
            tb_klient.k_nazwa,
            ts_regiony.rj_nazwa,
            tb_klient.rk_idrodzajklienta
           FROM (tb_klient
             LEFT JOIN ts_regiony USING (rj_idregionu))) o ON ((tg_zlecenia.k_idzlecajacy = o.k_idklienta)));
