CREATE VIEW raport_klienci AS
 SELECT tb_klient.k_idklienta,
    tb_klient.k_nazwa,
    tb_klient.rk_idrodzajklienta,
    tb_klient.k_ulica,
    tb_klient.k_nrlokalu,
    tb_klient.k_kodpocztowy,
    tb_klient.k_miejscowosc,
    tb_klient.pw_idpowiatu,
    tb_klient.k_nip,
    tb_klient.wk_idwagi,
    tb_klient.k_czykobieta,
    tb_klient.zi_idzrodla,
    tb_klient.k_telefon,
    tb_klient.k_email,
    tb_klient.sk_idstatusu,
    tb_klient.k_dlaczegoodszedl,
    tb_klient.k_zgodanaprzetw,
    tb_klient.k_opis,
    tb_klient.k_potrzeby,
    tb_klient.k_dostodb,
    tb_klient.k_osfizyczna,
    tb_klient.lk_czdomyslny,
    tb_klient.tgc_idgrupy,
    tb_klient.k_limitkredyt,
    tb_klient.k_kredytdni,
    tb_klient.p_idpracownika,
    tb_klient.p_dodajacy,
    tb_klient.k_datawpr,
    tb_klient.k_jegoagent,
    tb_klient.k_platnosc,
    tb_klient.k_kod,
    tb_klient.k_upust,
    tb_klient.k_flaga,
    tb_klient.k_nasznumer,
    tb_klient.rj_idregionu,
    tb_klient.k_osobaodbierajaca,
    tb_klient.k_procenthan,
    tb_klient.k_www,
    tb_klient.k_regon,
    tb_klient.k_inforejestr,
    tb_klient.k_koncesje,
    tb_klient.k_datakoncesji,
    tb_klient.k_iln,
    tb_klient.k_kodobcy,
    tb_klient.k_dostawa,
    tb_klient.sp_idspedytora,
    tb_klient.k_idplatnik,
    tb_klient.k_haslo,
    tb_klient.k_nrdomu,
    tb_klient.k_istniejeod,
    tb_klient.k_imie,
    tb_klient.k_nazwisko,
    tb_klient.k_idodbiorcy,
    tb_klient.k_kolor,
    tb_klient.k_zadluzenie,
    tb_klient.k_zadluzenieniezamk,
    tb_klient.k_zaliczka,
    tb_ludzieklienta.lk_imie,
    tb_ludzieklienta.lk_nazwisko,
    tb_ludzieklienta.lk_tytulstanowisko,
    tb_ludzieklienta.lk_stanowisko,
    tb_ludzieklienta.lk_ulica,
    tb_ludzieklienta.lk_nrlokalu,
    tb_ludzieklienta.lk_kodpocztowy,
    tb_ludzieklienta.lk_miejscowosc,
    ts_powiaty.pw_wojewodztwo,
    ts_regiony.rj_nazwa,
    ts_rodzajklienta.rk_typrodzaju
   FROM ((((tb_klient
     LEFT JOIN ts_powiaty USING (pw_idpowiatu))
     LEFT JOIN ts_regiony USING (rj_idregionu))
     LEFT JOIN tb_ludzieklienta ON ((tb_ludzieklienta.lk_idczklienta = tb_klient.lk_czdomyslny)))
     LEFT JOIN ts_rodzajklienta USING (rk_idrodzajklienta))
  WHERE (tb_klient.k_idklienta > 0);
