CREATE VIEW kv_raport_bystawka_detailed AS
 SELECT inn.tr_idtrans,
    sum(inn.v_netto) AS v_netto,
    sum(inn.v_vat) AS v_vat,
    sum(inn.v_vat2) AS v_vat2,
    sum(inn.v_vatb) AS v_vatb,
    sum(inn.v_vatb2) AS v_vatb2,
    sum(inn.v_brutto) AS v_brutto,
    sum(inn.v_netnetto) AS v_netnetto,
    sum(inn.v_netvat) AS v_netvat,
    sum(inn.v_netvat2) AS v_netvat2,
    sum(inn.v_netvatb) AS v_netvatb,
    sum(inn.v_netvatb2) AS v_netvatb2,
    sum(inn.v_netbrutto) AS v_netbrutto,
    inn.v_stvat,
    inn.v_zw,
    sum(inn.v_iloscwyd_sum) AS v_iloscwyd_sum,
    sum(inn.l_pozycji) AS l_pozycji,
    sum(inn.l_pozycjiusl) AS l_pozycjiusl,
    sum(inn.l_pozycji0) AS l_pozycji0,
    inn.v_iscorr AS v_zaokl,
    inn.v_kursdok,
    inn.v_iswal,
    inn.v_idwaluty
   FROM ( SELECT te.tr_idtrans,
            sum(te.v_netto) AS v_netto,
            round(public.vatfromnet(sum(te.v_netto), te.v_stvat), 2) AS v_vat,
            sum(te.v_vatn) AS v_vat2,
            round(public.vatfrombrt(sum(te.v_brutto), te.v_stvat), 2) AS v_vatb,
            sum(te.v_vatb) AS v_vatb2,
            sum(te.v_brutto) AS v_brutto,
            sum(te.v_netnetto) AS v_netnetto,
            round(public.vatfromnet(sum(te.v_netnetto), te.v_stvat), 2) AS v_netvat,
            sum(te.v_netvatn) AS v_netvat2,
            round(public.vatfrombrt(sum(te.v_netbrutto), te.v_stvat), 2) AS v_netvatb,
            sum(te.v_netvatb) AS v_netvatb2,
            sum(te.v_netbrutto) AS v_netbrutto,
            te.v_stvat,
            te.v_zw,
            sum(abs(te.v_iloscwyd)) AS v_iloscwyd_sum,
            sum(te.v_iloscpoz) AS l_pozycji,
            sum(te.v_iloscpozusl) AS l_pozycjiusl,
            sum(te.v_ilosc0cena) AS l_pozycji0,
            te.v_kurswal AS v_kursdok,
            te.v_iswal,
            te.v_idwaluty,
            te.v_iscorr
           FROM tb_vat te
          WHERE (te.v_isorg = ANY (ARRAY[0, 1]))
          GROUP BY te.tr_idtrans, te.v_stvat, te.v_zw, te.v_kurswal, te.v_iscorr, te.v_ispkormakro, te.v_iswal, te.v_idwaluty) inn
  GROUP BY inn.tr_idtrans, inn.v_stvat, inn.v_zw, inn.v_kursdok, inn.v_iswal, inn.v_idwaluty, inn.v_iscorr;
