CREATE TYPE dodaj_wz_type AS (
	tel_iloscf numeric,
	tel_idelem integer,
	tex_idelem integer,
	tr_idtrans integer,
	ttw_idtowaru integer,
	ttm_idtowmag integer,
	tmg_idmagazynu integer,
	k_idklienta integer,
	rc_data date,
	ttw_whereparams integer,
	ttw_inoutmethod integer,
	prt_idpartii integer,
	rez_idelem integer,
	tel_oidklienta integer,
	_pominrez boolean,
	rez_idelem2 integer,
	_isteex integer,
	fm_idcentrali integer
);
