CREATE TYPE triggerfunction AS ENUM (
    'AUTOREZERWACJEDOTE',
    'DELZEROREZ',
    'ZMNIEJSZREZERWACJEPZ',
    'CHECKRLP',
    'MARKTEASSAFEFORCHANGE',
    'MRPPALETALLOWCHANGEMMAG',
    'CHECKPZWARTOSCZEROILOSC'
);


SET search_path = gmr, pg_catalog;
