CREATE TABLE kh_deferredkh (
    dkh_id integer DEFAULT nextval('kh_deferredkh_s'::regclass) NOT NULL,
    fm_idcentrali integer NOT NULL,
    dkh_pkgid integer DEFAULT nextval('kh_deferredkh_s'::regclass) NOT NULL,
    dkh_outtype integer,
    ro_idroku integer NOT NULL,
    dkh_createdate timestamp without time zone DEFAULT now() NOT NULL,
    dkh_mayprocess boolean DEFAULT false NOT NULL,
    dkh_processeddate timestamp without time zone,
    dkh_errormessage text,
    dkh_errortype smallint,
    tr_idtrans integer,
    pl_idplatnosc integer,
    zk_idzapisu_out integer,
    rh_idrejestru_out integer,
    kp_idzapisu_out integer,
    dkh_kh_dz_iddziennika integer,
    dkh_kh_mn_miesiac integer,
    dkh_kh_wz_idwzorca integer,
    dkh_kh_checkdate boolean,
    dkh_rv_nr_idnazwy integer,
    dkh_rv_nr_idnazwy2 integer,
    dkh_rv_mc_wedlug smallint,
    dkh_rv_mc_ustalony integer,
    dkh_rv_k_wedlug smallint,
    dkh_rv_howodlvat smallint,
    dkh_rv_tworvneeded boolean,
    dkh_kpir_mn_miesiac integer,
    dkh_kpir_k_wedlug smallint,
    dkh_kpir_wzk_idwzorca integer,
    dkh_kpir_typlaczenia smallint,
    dkh_rv_kursvat mpq,
    dkh_rv_kursvat_idwaluty integer
);
