CREATE TABLE kh_konta (
    kt_idkonta integer DEFAULT nextval(('kh_konta_s'::text)::regclass) NOT NULL,
    kt_ref integer,
    kt_flaga integer DEFAULT 0,
    kt_prefix text,
    kt_numer text,
    kt_wn numeric DEFAULT 0,
    kt_ma numeric DEFAULT 0,
    kt_opis text,
    wl_idwaluty integer DEFAULT 1,
    k_idklienta integer,
    kt_data date DEFAULT now(),
    ro_idroku integer NOT NULL,
    kt_wnbuf numeric DEFAULT 0,
    kt_mabuf numeric DEFAULT 0,
    p_idpracownika integer,
    tmg_idmagazynu integer,
    bk_idbanku integer,
    zl_idzlecenia integer,
    kt_poziom smallint DEFAULT 0,
    kt_zerosto smallint DEFAULT 0,
    kt_iswymiar boolean DEFAULT false,
    kt_budzetwn numeric DEFAULT 0,
    kt_budzetma numeric DEFAULT 0,
    kt_budzetwnbuf numeric DEFAULT 0,
    kt_budzetmabuf numeric DEFAULT 0,
    kt_sdwnbuf numeric DEFAULT 0,
    kt_sdmabuf numeric DEFAULT 0,
    kt_sdwn numeric DEFAULT 0,
    kt_sdma numeric DEFAULT 0,
    ktn_idkonta integer,
    ktt_idtypu integer,
    ktt_idtypuinh integer
);
