CREATE TABLE kh_platnosci (
    pl_idplatnosc integer DEFAULT nextval(('kh_platnosci_s'::text)::regclass) NOT NULL,
    pl_wartosc numeric DEFAULT 0,
    pl_wplyw numeric DEFAULT 1,
    pl_pozostalo numeric DEFAULT 0,
    pl_formaplat integer DEFAULT 0,
    wl_idwaluty integer DEFAULT 0,
    pl_datawplywu date DEFAULT now(),
    p_idpracownika integer,
    k_idklienta integer,
    pl_seria character varying(4),
    pl_numer integer,
    pl_opis text,
    bk_idbanku integer,
    pl_flaga integer DEFAULT 0,
    pl_kompensata integer,
    wl_przelicznik mpq DEFAULT '1'::mpq,
    pl_numerref text,
    pl_nrobcy text,
    zl_idzlecenia integer,
    pl_sseria character varying(4),
    pl_tmp text,
    pl_idplatnoscskoj integer,
    fm_idcentrali integer,
    pl_wplnfifo numeric,
    lt_idtransportu integer,
    pl_saldokomp numeric DEFAULT 0,
    st_idstatusu integer,
    br_idrelacji integer,
    tr_idtrans integer,
    zd_idzdarzenia integer,
    pl_numerref2 text
);
