CREATE TABLE kh_zapisyhead (
    zk_idzapisu integer DEFAULT nextval(('kh_zapisyhead_s'::text)::regclass) NOT NULL,
    dz_iddziennika integer,
    ro_idroku integer,
    mn_miesiac integer,
    zk_numer integer DEFAULT 0,
    zk_datawpisu date DEFAULT now(),
    zk_dataopgosp date,
    zk_datadok date,
    zk_numerdowodu text,
    zk_opis text,
    zk_wn numeric DEFAULT 0,
    zk_ma numeric DEFAULT 0,
    p_idpracownika integer,
    p_ksiegujacy integer,
    zk_flaga integer DEFAULT 0,
    zk_fullnumer text,
    tr_idtrans_wkh integer,
    zk_typ smallint DEFAULT 1,
    zk_lockby integer,
    zk_lockdate timestamp with time zone,
    zk_dorozpisaniaelemswkh integer DEFAULT 0,
    zk_dorozpisaniaelemswkh_nnull integer DEFAULT 0,
    tr_idtrans integer
);
