CREATE TABLE kh_zapisykpir (
    kp_idzapisu integer DEFAULT nextval(('kh_zapisykpir_s'::text)::regclass) NOT NULL,
    kp_operacjagos text,
    kp_flaga integer DEFAULT 0,
    k_idklienta integer,
    kp_kadres text,
    kp_knazwa text,
    kp_nip text,
    kp_kkodpocz text,
    kp_kmiasto text,
    kp_pozycja integer,
    ro_idroku integer,
    kp_dataop date,
    mn_miesiac integer,
    kp_numerdok text,
    kp_uwagi text,
    kp_sprzedaz numeric DEFAULT 0,
    kp_sprzedpoz numeric DEFAULT 0,
    kp_zakup numeric DEFAULT 0,
    kp_koszty numeric DEFAULT 0,
    kp_reklama numeric DEFAULT 0,
    kp_wyplaty numeric DEFAULT 0,
    kp_wydatkipoz numeric DEFAULT 0
);
