CREATE TABLE kr_rozrachunki (
    rr_idrozrachunku integer DEFAULT nextval('kr_rozrachunki_s'::regclass) NOT NULL,
    k_idklienta integer,
    kt_idkonta integer,
    tr_idtrans integer,
    pl_idplatnosc integer,
    zp_idelzapisu integer,
    rr_idwaluty integer,
    rr_kwotawnwal numeric DEFAULT 0,
    rr_kwotamawal numeric DEFAULT 0,
    rr_wartoscwnpln numeric DEFAULT 0,
    rr_wartoscmapln numeric DEFAULT 0,
    rr_wartoscwnpozwal numeric DEFAULT 0,
    rr_wartoscmapozwal numeric DEFAULT 0,
    rr_wartoscwnpozpln numeric DEFAULT 0,
    rr_wartoscmapozpln numeric DEFAULT 0,
    rr_kwotawal numeric DEFAULT 0,
    rr_wartoscpln numeric DEFAULT 0,
    rr_wartoscpozwal numeric DEFAULT 0,
    rr_wartoscpozpln numeric DEFAULT 0,
    rr_iswn boolean NOT NULL,
    rr_isbufor boolean NOT NULL,
    rr_isnormal boolean NOT NULL,
    rr_datadokumentu date,
    rr_dataplatnosci date,
    rr_flaga integer DEFAULT 0,
    rr_srcid integer,
    rr_opis text,
    rr_datazaplacenia date,
    fm_idcentrali integer,
    sd_idsalda integer,
    zp_idelzapisurk integer,
    rr_no smallint DEFAULT 0,
    st_idstatusu integer,
    rr_formaplat integer,
    rr_kwotawalfornorm numeric NOT NULL,
    bk_idbanku integer
);
