CREATE TABLE st_srodkitrwale (
    str_id integer DEFAULT nextval(('st_srodkitrwale_s'::text)::regclass) NOT NULL,
    str_nrinwent text,
    gst_id integer,
    str_kst text DEFAULT ''::character varying,
    str_rodzajst integer DEFAULT 1 NOT NULL,
    str_nazwa text,
    str_opis text,
    str_stawkaam numeric,
    str_wartpocz numeric,
    str_wartbiez numeric,
    str_wartumoz numeric,
    str_dataewid date DEFAULT now() NOT NULL,
    str_datapocz date,
    str_datarozp date,
    str_datalikw date,
    str_rodzajam integer DEFAULT 1 NOT NULL,
    str_aktywny integer,
    str_wartprzen numeric DEFAULT 0,
    str_wartosczdarzen numeric DEFAULT 0.00,
    str_wartoscplanu numeric DEFAULT 0.00,
    str_nrdokkupna text,
    str_uwagilikwidacji text,
    str_flaga integer DEFAULT 0,
    str_stawkaamkoszt numeric,
    str_wartbiezkoszt numeric DEFAULT 0,
    str_wartumozkoszt numeric DEFAULT 0,
    str_wartprzenkoszt numeric DEFAULT 0,
    str_wartoscplanukoszt numeric DEFAULT 0,
    str_wartosczdarzenkoszt numeric DEFAULT 0,
    str_wartpoczkoszt numeric,
    fm_idcentrali integer,
    tr_idtrans integer,
    fm_idoddzialu integer,
    p_idpracownika integer
);
