CREATE TABLE tb_firma (
    fm_index integer DEFAULT nextval(('tb_firma_s'::text)::regclass) NOT NULL,
    fm_nazwa text,
    fm_adres text,
    fm_kod text,
    fm_miejscowosc text,
    fm_nip text,
    fm_regon text,
    fm_tel1 text,
    fm_tel2 text,
    fm_fax text,
    fm_www text,
    fm_email text,
    fm_daneurz text,
    fm_flagacentr integer,
    fm_iln text,
    fm_uskarbowy text,
    fm_nazwisko text,
    fm_imie text,
    fm_dataurodzenia date,
    pw_idpowiatu integer,
    fm_wojewodztwo text,
    fm_powiat text,
    fm_gmina text,
    fm_poczta text,
    fm_repimie text,
    fm_repnazwisko text,
    fm_nazwaskr text,
    fm_nazwa2 text,
    fm_krs text,
    fm_kapitalzak text,
    fm_idcentrali integer,
    tgc_idgrupyceny integer,
    fm_idindextab integer,
    fm_colorscheme integer
);
