CREATE TABLE tb_kalendarzhead (
    kalh_idkalendarzahead integer DEFAULT nextval('tb_kalendarzhead_s'::regclass) NOT NULL,
    p_idpracownika integer NOT NULL,
    kalh_datautworzenia timestamp with time zone DEFAULT now(),
    kalh_miesiac integer,
    kalh_datastartmies date,
    kalh_datastopmies date,
    kalh_wynagrodzeniea numeric DEFAULT 0,
    kalh_wynagrodzenieb numeric DEFAULT 0,
    kalh_rbhpraca numeric DEFAULT 0,
    kalh_rbhurlop numeric DEFAULT 0,
    kalh_rbhnormatyw numeric DEFAULT 0,
    kalh_rbhchorobowe numeric DEFAULT 0,
    kalh_rbhinne numeric DEFAULT 0,
    kalh_rbhobecnosc numeric DEFAULT 0,
    kalh_rbhfirma numeric DEFAULT 0,
    kalh_kosztrbh numeric DEFAULT 0,
    kalh_dataaktrbh timestamp with time zone,
    kalh_dataaktkosztu timestamp with time zone,
    kalh_skrypt text DEFAULT 'Nie przeliczono'::text,
    kalh_opis text DEFAULT ''::text,
    kalh_rodzaj integer,
    kalh_flaga integer DEFAULT 0,
    fm_idcentrali integer,
    kalh_rbhodebranienadgodzin numeric DEFAULT 0,
    kalh_kosztrbhnetto numeric DEFAULT 0,
    kalh_kosztrbhwsp numeric DEFAULT 100,
    kalh_wartoscrbhnetto numeric DEFAULT 0,
    kalh_wartoscrbh numeric DEFAULT 0
);
