CREATE TABLE tb_pracownicy (
    p_idpracownika integer DEFAULT nextval(('tb_pracownicy_s'::text)::regclass) NOT NULL,
    p_nazwisko text NOT NULL,
    p_imie text NOT NULL,
    p_login text NOT NULL,
    p_adres text NOT NULL,
    p_kodpocztowy text NOT NULL,
    p_miejscowosc text NOT NULL,
    p_telefonkom text,
    p_telefondom text,
    p_email text,
    p_czyaktywny boolean DEFAULT true,
    st_idstanowiska integer DEFAULT 0,
    dz_iddzialu integer DEFAULT 0,
    p_nic2 character varying(3),
    p_pokazdok integer,
    p_zablokowany integer,
    tgr_idgrupy integer DEFAULT 0,
    p_procenthan numeric,
    k_idagenta integer,
    p_flaga integer,
    p_uprawnienia integer DEFAULT 0,
    p_kosztnah numeric DEFAULT 0,
    p_firma integer,
    p_karttow_podglad integer DEFAULT 0,
    p_karttow_edycja integer DEFAULT 0,
    p_karttow_edycjacen integer DEFAULT 0,
    k_defklient integer DEFAULT 0,
    p_mlimit numeric DEFAULT 0,
    p_przekazaniekomu integer,
    mbs_aptype smallint DEFAULT 12,
    p_maxrabat numeric DEFAULT 100,
    p_zadluzenie numeric[],
    p_periodrejestr_s integer DEFAULT 0,
    p_uprawnienia2 integer DEFAULT 0,
    p_wynagrodzenie numeric DEFAULT 0,
    p_kolor integer DEFAULT (power((2)::double precision, (24)::double precision) - (1)::double precision),
    p_defworkstarttime integer DEFAULT (8 * 60) NOT NULL,
    p_defworkendtime integer DEFAULT (16 * 60) NOT NULL,
    p_uprkkienta integer DEFAULT 0,
    p_uprawnienia3 integer DEFAULT ((1 << 4) | (1 << 5)),
    p_kodkreskowy text,
    p_telefonnrwew text,
    p_voipaccountid integer,
    p_kosztnahnetto numeric DEFAULT 0,
    p_narzutprocent numeric DEFAULT 100
);
