CREATE TABLE tb_zdarzenia (
    zd_idzdarzenia integer DEFAULT nextval(('tb_zdarzenia_s'::text)::regclass) NOT NULL,
    p_wpisujacy integer DEFAULT 0,
    p_idpracownika integer DEFAULT 0,
    k_idklienta integer DEFAULT 0,
    lk_idczklienta integer DEFAULT 0,
    ob_idobiektu integer DEFAULT 0,
    zl_idzlecenia integer DEFAULT 0,
    zd_datautworzenia timestamp with time zone DEFAULT now() NOT NULL,
    zd_datarozpoczecia timestamp with time zone NOT NULL,
    zd_datazakonczenia timestamp with time zone NOT NULL,
    zd_dataprzypomnienia timestamp with time zone,
    zd_miejsce text,
    zd_temat text,
    zd_opis text,
    zd_rodzaj integer DEFAULT 0,
    zd_typzdarzenia integer DEFAULT 0,
    zd_flaga integer DEFAULT 0 NOT NULL,
    st_idstatusu integer,
    zd_prefix text,
    zd_numer integer,
    zd_koszt numeric DEFAULT 0,
    wl_idwaluty integer DEFAULT 1,
    p_pracprzyp integer DEFAULT 0,
    zd_extid text,
    szl_idstatusu integer DEFAULT 0,
    zd_idparent integer,
    zd_lp integer,
    zd_lpprefix text,
    plt_id integer,
    _zl_idticketu integer,
    zd_terminzakonczenia timestamp with time zone,
    zd_aktualnieu integer,
    dz_iddzialu integer,
    zdp_id integer,
    zdl_id integer,
    zd_opishtml text,
    rol_id integer,
    pz_idplanu integer,
    zd_datamodyfikacji timestamp with time zone DEFAULT now(),
    zd_rbh numeric DEFAULT 0,
    zd_rbhdzieci numeric DEFAULT 0,
    zd_procwyk integer DEFAULT 0,
    zd_datawykonania timestamp with time zone,
    zd_priority integer DEFAULT nextval('zd_priority_upper'::regclass),
    zd_lockby integer,
    zd_lockdate timestamp with time zone,
    _zd_from text,
    _zd_to text,
    _zd_mid text,
    _zd_mid_replayto text,
    _zd_thread integer,
    zd_wersja integer,
    zd_idrewizja integer,
    zd_stprojektu smallint DEFAULT (1 << 2),
    zd_platnosciwnlpn numeric DEFAULT 0,
    zd_platnoscimalpn numeric DEFAULT 0,
    zd_pozycjanaprocedurzesprawy text,
    zd_mail_id integer,
    zd_plczastrwania integer DEFAULT 0 NOT NULL,
    zd_lt_idtransportu integer,
    zd_wersjasprawy integer,
    zd_custom text
);
