CREATE TABLE tg_archiwum (
    a_idarchiwum integer DEFAULT nextval(('tg_archiwum_s'::text)::regclass) NOT NULL,
    a_rodzaj integer,
    a_faxmail integer,
    k_idklienta integer,
    lk_idczklienta integer,
    p_idpracownika integer,
    a_old_temat character varying(150),
    a_status integer,
    a_zalacznik text,
    a_datanadold date DEFAULT now(),
    a_dataarchiwizacji date,
    a_zrodlo text,
    a_job text,
    a_iloscprob integer DEFAULT 0,
    a_dataold timestamp with time zone,
    a_datanadejscia timestamp with time zone,
    zl_idzlecenia integer,
    a_temat text,
    a_prefix text,
    a_numer integer,
    a_datanadania date DEFAULT now(),
    a_koszt numeric DEFAULT 0,
    r_idrodzaju integer DEFAULT 0,
    wl_idwaluty integer DEFAULT 1
);
