CREATE TABLE tg_documentmasterelem (
    dme_idelem integer DEFAULT nextval('tg_documentmasterelem_s'::regclass) NOT NULL,
    ob_idobiektu integer,
    dme_sn text DEFAULT ''::text,
    dme_mac text DEFAULT ''::text,
    dme_ip text DEFAULT ''::text,
    dme_time timestamp with time zone,
    dme_datautw timestamp with time zone DEFAULT now() NOT NULL,
    dme_flaga integer DEFAULT 0,
    dme_tonerblack integer DEFAULT 0,
    dme_tonercyan integer DEFAULT 0,
    dme_tonermagenta integer DEFAULT 0,
    dme_toneryellow integer DEFAULT 0,
    dme_cntmain integer DEFAULT 0,
    dme_cntcopierbw integer DEFAULT 0,
    dme_cntcopiercolor integer DEFAULT 0,
    dme_cntprinterbw integer DEFAULT 0,
    dme_cntprintercolor integer DEFAULT 0,
    dme_cntscannerbw integer DEFAULT 0,
    dme_cntscannercolor integer DEFAULT 0,
    dme_cntfaxbw integer DEFAULT 0,
    dme_cntfaxcolor integer DEFAULT 0,
    dme_cntfaxsentbw integer DEFAULT 0,
    dme_cntfaxsentcolor integer DEFAULT 0,
    dme_eventkcnt integer DEFAULT 0,
    dme_eventccnt integer DEFAULT 0,
    dme_eventmcnt integer DEFAULT 0,
    dme_eventycnt integer DEFAULT 0
);
