CREATE TABLE tg_listprzewozowy (
    lt_idtransportu integer NOT NULL,
    lp_waga numeric DEFAULT 0,
    lp_paczek40t50 integer DEFAULT 0,
    lp_formaplatnosci integer,
    lp_ktoplaci integer DEFAULT 0,
    lp_pobranie numeric,
    lp_email text,
    lk_idczklienta integer,
    lp_wartoscprzesylki numeric,
    lp_adr_nazwa text,
    lp_adr_ulica text,
    lp_adr_kodpocztowy text,
    lp_adr_miejscowosc text,
    lp_telefon text,
    lp_zawartosc text,
    lp_adr_nrdomu text,
    lp_ubezpieczenie numeric DEFAULT 0,
    lp_flaga integer DEFAULT 0,
    lp_usluga integer DEFAULT 1,
    lp_n1 text,
    lp_n2 text,
    lp_czklienta text,
    lp_platnik integer,
    lp_nrobcy text,
    lp_punktwydania text,
    lp_useadres integer DEFAULT 0,
    lpz_idzbioru integer,
    lp_dane_dodatkowe text,
    lp_data_zaladunek timestamp without time zone,
    lp_data_dostawy timestamp without time zone
);
