CREATE TABLE tg_obiekty (
    ob_idobiektu integer DEFAULT nextval(('tg_obiekty_s'::text)::regclass) NOT NULL,
    ob_kod text DEFAULT ''::character varying,
    ob_nazwa text DEFAULT ''::text,
    k_idklienta integer,
    ob_lokalizacja text DEFAULT ''::text,
    ob_opis text DEFAULT ''::text,
    ttw_idtowaru integer,
    ob_nrseryjny text DEFAULT ''::character varying,
    ob_datapoczatkowa date DEFAULT now(),
    ob_datakoncowa date DEFAULT now(),
    ob_flaga integer DEFAULT 0,
    ob_ref integer,
    ob_poczgwarancji date DEFAULT now(),
    ob_koniecgwarancji date DEFAULT (now() + '1 year'::interval),
    ob_cecha1 text,
    ob_cecha2 text,
    ob_cecha3 text,
    ob_srcid integer,
    ob_seria character varying(4),
    rb_idrodzaju integer,
    w_idwydzialu integer,
    ob_kosztpracy numeric DEFAULT 0,
    ob_pojemnoscnah numeric DEFAULT 0,
    st_idstatusu integer,
    p_idpracownika integer,
    ob_srctype integer,
    tjn_idjednprzebieg integer,
    ob_kolor integer DEFAULT (power((2)::double precision, (24)::double precision) - (1)::double precision),
    ob_tmpflaga integer,
    ob_lockby integer,
    ob_lockdate timestamp with time zone
);
