CREATE TABLE tg_swiadectwa (
    sw_idswiadectwa integer DEFAULT nextval('tg_swiadectwa_s'::regclass) NOT NULL,
    ttw_idtowaru integer,
    k_idklienta integer,
    tmg_idmagazynu integer,
    p_idpracownika integer,
    sw_rok character varying(2),
    sw_numer integer,
    sw_seria character varying(4),
    sw_nrkolojnyproby integer,
    sw_sufixproby text,
    sw_numerproby text,
    sw_waganetto numeric,
    sw_wagabrutto numeric,
    sw_dataprzyjecia date,
    sw_databadania date,
    sw_flaga integer DEFAULT 0,
    sw_rodzaj integer,
    sw_uwagi text,
    st_idstatusu integer,
    sw_ilosczafakturowana numeric DEFAULT 0,
    fm_idcentrali integer,
    sw_wagauklienta numeric DEFAULT 0
);
