CREATE TABLE tg_transport (
    lt_idtransportu integer DEFAULT nextval(('tg_transport_s'::text)::regclass) NOT NULL,
    lt_data timestamp with time zone DEFAULT now(),
    lt_seria character varying(4),
    lt_numer integer,
    lt_rok character varying(2),
    k_idklienta integer,
    sp_idspedytora integer,
    ob_idobiektu integer,
    p_idpracownika integer,
    lt_nrobcy text,
    lt_uwagi text,
    sl_idstatusu integer,
    lt_rodzaj integer,
    lt_flaga integer DEFAULT 0,
    lt_koszt numeric,
    st_idstatusu integer,
    lt_konwojent integer,
    lt_stanlicznikastart numeric,
    lt_stanlicznikastop numeric,
    fm_idcentrali integer,
    lt_kierowca text,
    lt_samochod text,
    lt_data_zakonczenia timestamp with time zone,
    lt_wyplaty numeric DEFAULT 0,
    lt_nierozliczone numeric DEFAULT 0,
    lt_dokkoszt numeric DEFAULT 0,
    lt_dokkosztbrt numeric DEFAULT 0,
    lt_rozliczenia numeric DEFAULT 0,
    lt_celwyjazdu text,
    lt_celpodrozy text,
    lt_data_dostarczenia timestamp with time zone DEFAULT now() NOT NULL,
    lt_osoba_odbierajaca text,
    fm_index integer NOT NULL,
    lt_zlecajacy integer,
    lt_przyczepa text,
    lt_obprzyczepa integer,
    wt_idwymagania integer,
    lt_telkierowcy text,
    lt_telkonwojenta text,
    lt_kosztnag numeric,
    lt_kosztnagwal integer,
    lt_kilometrow numeric,
    lt_obcykonwojent text,
    lt_miejscezaladunku integer,
    lt_miejscedostawy integer
);
