CREATE TABLE tg_transelem (
    tel_idelem integer DEFAULT nextval(('tg_transelem_s'::text)::regclass) NOT NULL,
    ttm_idtowmag integer DEFAULT 0,
    tr_idtrans integer DEFAULT 1,
    tel_nazwa text DEFAULT ''::text,
    tel_skojzam integer,
    tel_iloscpkor numeric DEFAULT 0,
    tel_stvat numeric DEFAULT 22,
    tel_wartoscclo numeric DEFAULT 0,
    tel_cenabdok numeric DEFAULT 0,
    tel_clo numeric DEFAULT 0,
    tel_iloscwyd numeric DEFAULT 0,
    tel_rabatdb numeric,
    tel_sprzedaz integer DEFAULT '-2'::integer,
    tel_kosztnabycia numeric DEFAULT 0,
    ttw_idtowaru integer,
    tel_flaga integer DEFAULT 0,
    tel_ilosc numeric DEFAULT 0,
    tel_cena0 numeric DEFAULT 0,
    tel_cenawal numeric DEFAULT 0,
    tel_walutawal smallint DEFAULT 0,
    tel_cenadok numeric DEFAULT 0,
    tjn_idjedn smallint DEFAULT 1,
    tel_iloscop numeric DEFAULT 0,
    tjn_opakow smallint DEFAULT 1,
    tel_grupacen smallint DEFAULT 0,
    tel_skojarzony integer,
    tel_kurswal mpq DEFAULT '1'::mpq,
    tel_koszt numeric DEFAULT 0,
    tel_skojlog integer,
    tel_idklienta integer DEFAULT 0,
    tel_nrzam text DEFAULT ''::character varying,
    tel_cenabwal numeric DEFAULT 0,
    tel_cecha text,
    tel_lp integer DEFAULT 0,
    tel_iloscf numeric,
    tel_kursdok mpq DEFAULT '1'::mpq,
    tel_narzut numeric DEFAULT 0,
    tel_ilosckomp numeric DEFAULT 0,
    tel_wartosczakupu numeric DEFAULT 0,
    tel_uwagi text,
    tel_nadmiarzam numeric DEFAULT 0,
    tel_zaokraglenia numeric DEFAULT 0,
    tel_datawazn date DEFAULT now(),
    tel_oidklienta integer,
    tel_newflaga integer DEFAULT 0,
    p_idpracownika integer,
    tel_skojzestaw integer,
    opk_idosrodka integer,
    st_idstatusu integer,
    a_idakcji integer,
    tel_wnettodok numeric,
    tel_wnettowal numeric DEFAULT 0,
    tel_datauklienta date,
    tel_iloscdorezerwacji numeric,
    tel_przelnilosci numeric DEFAULT 1000,
    tel_przelnopakow numeric DEFAULT 1000,
    tel_opishtml text,
    tel_cenakgodok numeric DEFAULT 0,
    tel_lpprefix text DEFAULT ''::text,
    tel_new2flaga integer DEFAULT 0,
    tel_iloscfresttoex numeric DEFAULT 0,
    prt_idpartii integer,
    tel_nrpartii text,
    tel_datazam date,
    pz_idplanusrc integer,
    tel_cenanettods numeric,
    tel_walutads integer,
    tel_procodlvat numeric DEFAULT 100 NOT NULL,
    tel_dokladnoscflags smallint DEFAULT ((2 << 0) & 15),
    tel_skojzamtex integer,
    th_idtechnologii integer,
    tel_iloscpotr numeric DEFAULT 0 NOT NULL,
    rmp_idsposobu integer,
    tel_cenanettoto numeric,
    tel_walutato integer,
    tel_new3flaga integer DEFAULT 0 NOT NULL
);


SET search_path = gm, pg_catalog;
