CREATE TABLE tg_transakcje (
    tr_idtrans integer DEFAULT nextval(('tg_transakcje_s'::text)::regclass) NOT NULL,
    tr_rok character varying(2) DEFAULT '01'::character varying,
    tr_numer integer,
    tr_rodzaj integer DEFAULT 0,
    tr_sprzedaz integer DEFAULT '-1'::integer,
    p_idpracownika integer DEFAULT 0,
    tr_datasprzedaz date DEFAULT now(),
    tr_datawystaw date DEFAULT now(),
    wl_idwaluty integer DEFAULT 1,
    k_idklienta integer DEFAULT 0,
    tr_knazwa text DEFAULT ''::text,
    tr_kadres text DEFAULT ''::text,
    tr_nip text DEFAULT ''::character varying,
    tr_dataplatnosci date DEFAULT (now() + '14 days'::interval),
    tr_opis text DEFAULT ''::text,
    tr_wartosc numeric DEFAULT 0,
    tr_dozaplaty numeric DEFAULT 0,
    tr_zaplacono numeric DEFAULT 0,
    tr_kosztkraj numeric DEFAULT 0,
    tr_przelicznik mpq DEFAULT '1'::mpq,
    tr_vatsad numeric DEFAULT 0,
    tr_vat numeric DEFAULT 0,
    tr_kkodpocz text DEFAULT ''::character varying,
    tr_skojarzona integer DEFAULT 0,
    tr_nrobcy text,
    tr_formaplat smallint DEFAULT 0,
    tr_oadres text DEFAULT ''::character varying,
    tr_omiasto text DEFAULT ''::character varying,
    tr_okodpocz text DEFAULT ''::character varying,
    tr_oidklienta integer DEFAULT 0,
    tmg_idmagazynu integer DEFAULT 1,
    tr_onip text DEFAULT ''::character varying,
    tr_marza numeric DEFAULT 0,
    tr_zaliczka numeric DEFAULT 0,
    tr_zamknieta integer DEFAULT 0,
    tr_zaliczonedla integer DEFAULT 0,
    tr_grupacen smallint DEFAULT 1,
    tr_narzecz integer,
    tr_kmiasto text,
    tr_koszt numeric DEFAULT 0,
    zl_idzlecenia integer,
    tr_onazwa text DEFAULT ''::text,
    tr_kosztzag numeric DEFAULT 0,
    tr_numerdost text DEFAULT ''::character varying,
    tr_numerzam text DEFAULT ''::character varying,
    tr_seria character varying(4) DEFAULT ''::character varying,
    tr_inne text DEFAULT ''::character varying,
    st_idstatusu integer,
    tr_flaga integer DEFAULT 0,
    tr_longopis text DEFAULT ''::text,
    tr_skojwyn integer,
    tr_skojlog integer,
    tr_warunki text,
    tr_zaliczonoukl integer,
    tr_wymaganazaliczka numeric,
    sp_idspedytora integer,
    lt_idtransportu integer,
    tmg_idmagazynu2 integer,
    tr_krolnik text,
    tr_orolnik text,
    fm_index integer NOT NULL,
    tr_datauklienta date DEFAULT now(),
    tr_idczklienta integer,
    fm_idcentrali integer,
    br_idrelacji integer,
    tr_skojzam integer,
    tr_sposobreal integer,
    tr_idspakowal integer,
    pz_idplanu integer,
    mbs_aptype smallint DEFAULT 12,
    tr_kursvat mpq,
    sp_idprzechow integer,
    tr_data4 date,
    tr_idczklienta2 integer,
    tr_newflaga integer DEFAULT 0,
    tr_idkraju integer,
    tr_oidkraju integer,
    tr_plikwydruku text,
    tr_lockby integer,
    tr_kolor integer DEFAULT (power((2)::double precision, (24)::double precision) - (1)::double precision),
    tr_infix text,
    tr_platnosciwnlpn numeric DEFAULT 0,
    tr_platnoscimalpn numeric DEFAULT 0,
    tr_datawpr timestamp with time zone DEFAULT now(),
    tr_datazamk timestamp with time zone,
    tr_kontakt text,
    mm_idmiejscactx integer,
    tr_datafiskalizacji timestamp with time zone,
    pwep_idpunktu integer,
    tr_wagabrutto numeric DEFAULT 0,
    k_agentsp integer,
    tr_wersja text,
    szt_id integer,
    bk_idbankuwal integer,
    bk_idbankupln integer,
    p_zamykajacy integer
);


SET search_path = gm, pg_catalog;
