CREATE TABLE tg_towary (
    ttw_idtowaru integer DEFAULT nextval(('tg_towary_s'::text)::regclass) NOT NULL,
    tgr_idgrupy integer DEFAULT 1,
    ttw_nazwa text DEFAULT 'Nowy towar'::text,
    ttw_opis text DEFAULT ''::text,
    ttw_vatz numeric DEFAULT 23,
    ttw_vats numeric DEFAULT 23,
    ttw_stanmin numeric DEFAULT 0,
    ttw_stanmax numeric DEFAULT 0,
    tjn_idjedn integer DEFAULT 1,
    ttw_nazwadost text DEFAULT ''::character varying,
    ttw_usluga boolean DEFAULT false,
    ttw_klucz text DEFAULT ''::character varying,
    ttw_sww text DEFAULT ''::character varying,
    ttw_aktywny smallint DEFAULT 1,
    br_idbranzy integer DEFAULT 0,
    ttw_datawpr date DEFAULT now(),
    ttw_dataostmod date DEFAULT now(),
    ttw_dostawca integer DEFAULT 0,
    tpg_idpodgrupy integer DEFAULT 0,
    ttw_cenabiletu numeric DEFAULT 0,
    ttw_cenabaz numeric DEFAULT 0,
    ttw_rbh numeric DEFAULT 0,
    ttw_koddost text DEFAULT ''::character varying,
    ttw_longopis text DEFAULT ''::text,
    ttw_clo numeric DEFAULT 0,
    ttw_waznydni integer DEFAULT 0,
    ttw_n1 text DEFAULT ''::character varying,
    ttw_n2 text DEFAULT ''::character varying,
    ttw_n3 text DEFAULT ''::character varying,
    ttw_waga numeric DEFAULT 0,
    ttw_tk integer,
    ttw_tkopakow integer,
    ttw_tkopakow2 integer,
    ttw_akcyza numeric,
    ttw_ean text,
    ttw_formula text,
    ttw_procenthan numeric DEFAULT 0,
    ttw_idwalutybaz integer DEFAULT 0,
    ttw_objetosc_l numeric DEFAULT 0,
    tjn_dostawca integer,
    ttw_gwarancja integer,
    zl_idzlecenia integer,
    ttw_kosztpr numeric DEFAULT 100,
    ttw_kosztkw numeric DEFAULT 0,
    ttw_vatm numeric DEFAULT 0,
    ttw_pcn text,
    ttw_wagaoppod numeric DEFAULT 0,
    ttw_kontokh1 text,
    ttw_kontokh2 text,
    ttw_flaga integer DEFAULT 0,
    ttw_krotnoscgen numeric,
    ttw_limitjest integer,
    ttw_sumkwm numeric DEFAULT 0,
    ttw_cenadef numeric DEFAULT 0,
    ttw_wlcenadef integer DEFAULT 1,
    ttw_idopakowania integer,
    ttw_idopakowania2 integer,
    ttw_n4 text,
    ttw_n5 text,
    ttw_n6 text,
    tmg_idonlymagazynu integer,
    ttw_opkidosrodka integer,
    tgw_idgrupy integer,
    st_idstatusu integer,
    ttw_newflaga integer DEFAULT 0,
    ttw_producent integer,
    ttw_minwielzam numeric DEFAULT 0,
    ttw_stan numeric[],
    ttw_rezerwacja numeric[],
    ttw_bilanstk numeric[],
    ttw_ostcena numeric[],
    ttw_idostwaluty integer[],
    ttw_ostatniadostawa integer[],
    ttw_wartosc numeric[],
    ttw_cenasr numeric[],
    ttw_bkorderminus numeric[],
    ttw_bkorderplus numeric[],
    ttw_www text,
    ttw_inoutmethod integer DEFAULT 0,
    ttw_mmwdrodze numeric[],
    ttw_opishtml text,
    ttw_ostcenanab numeric[],
    ttw_powierzchnia_l numeric DEFAULT 0,
    ttw_czasdostawy integer DEFAULT 0,
    ttw_pracownikwpr integer,
    ttw_sprzedazall numeric[],
    ttw_zakupall numeric[],
    ttw_domyslnareceptura integer[],
    ttw_kgo numeric DEFAULT 0,
    ttw_dlugosc_l numeric DEFAULT 0,
    tmg_magazynprod integer,
    ttw_mwo_dynamiczne numeric DEFAULT 0,
    ttw_mwo_statyczne numeric DEFAULT 0,
    ttw_domyslnatechnologia integer[],
    ttw_strukturakonstrukcyjna integer[],
    ttw_kolor integer DEFAULT (power((2)::double precision, (24)::double precision) - (1)::double precision),
    ttw_lockby integer,
    ttw_lockdate timestamp with time zone,
    ttw_rezlekka numeric[],
    ttw_whereparams integer DEFAULT 0,
    ttw_pzhashmethod integer DEFAULT 0,
    ttw_wzhashmethod integer DEFAULT 0,
    ttw_domyslnatechnoserwis integer[],
    ttw_domyslnatechnobadania integer[],
    fm_idonlycentrali integer,
    ttw_idxsufix text,
    ttw_parentkod text,
    ttw_idxref integer,
    ttw_dlugosccykluprod integer DEFAULT 0 NOT NULL,
    ttw_czaspreorder integer DEFAULT 0 NOT NULL,
    ttw_defprocodlvat numeric DEFAULT 100 NOT NULL,
    ttw_idxinfix text,
    ttw_dokladnoscflags integer DEFAULT ((2 << 0) | (2 << 4)),
    ttw_blokady integer DEFAULT 0,
    k_idonlyklienta integer,
    rk_idrodzajklientaonly integer,
    ttw_ja_idjednzakupu integer,
    ttw_ja_idjednsprzedazy integer,
    ttw_ja_idjedninwentaryzacji integer,
    ttw_dlugosc_m numeric DEFAULT 1,
    ttw_powierzchnia_m numeric DEFAULT 1,
    ttw_objetosc_m numeric DEFAULT 1,
    ttw_dlugosc_mpq mpq,
    ttw_powierzchnia_mpq mpq,
    ttw_objetosc_mpq mpq,
    ttw_new2flaga integer DEFAULT 0 NOT NULL,
    ttw_rtowaru integer NOT NULL,
    rmr_idrodzaju integer,
    rmp_idsposobu integer
);
