CREATE TABLE tg_voucher (
    vc_idvoucher integer DEFAULT nextval(('tg_voucher_s'::text)::regclass) NOT NULL,
    vc_rok character varying(2),
    vc_seria character varying(4),
    vc_numer integer,
    zl_idzlecenia integer,
    vc_nazwa text,
    vc_from text,
    vc_accomodation text,
    k_idklienta integer,
    vc_town text,
    vc_hotel text,
    vc_in date,
    vc_out date,
    vc_meals text,
    vc_transfers_data1 date,
    vc_transfers_routing1 text,
    vc_transfers_data2 date,
    vc_transfers_routing2 text,
    vc_language text,
    vc_programme text,
    vc_otherservices text,
    vc_remarks text,
    vc_payment text,
    p_idpracownika integer,
    vd_data date DEFAULT now(),
    vc_flaga integer
);
