CREATE TABLE tr_dyspozycjamag (
    dmag_iddyspozycji integer DEFAULT nextval('tr_dyspozycjamag_s'::regclass) NOT NULL,
    kwh_idheadu integer,
    ttw_idtowaru integer,
    ttm_idtowmag integer,
    knr_idelemu integer,
    knr_idelemu_idx integer,
    kwe_idelemu integer,
    knw_idelemu_koop integer,
    knw_idelemu integer,
    mrpp_idpalety integer,
    prt_idpartiipz integer,
    prt_idpartiiwz integer,
    p_idpracownika integer,
    rmp_idsposobu integer,
    dmag_ilosc numeric DEFAULT 0,
    dmag_iloscwmag numeric DEFAULT 0,
    dmag_iloscwmagclosed numeric DEFAULT 0,
    dmag_znacznik text,
    dmag_typ integer DEFAULT 0,
    dmag_wplywmag integer DEFAULT 0,
    dmag_data timestamp without time zone DEFAULT now(),
    dmag_flaga integer DEFAULT 0,
    tmg_idmagazynu integer,
    dmag_wagaop numeric DEFAULT 0,
    zl_idzlecenia integer,
    dmag_serialno text,
    dmag_idparent integer,
    dmag_datautw timestamp without time zone DEFAULT now()
);
