CREATE TABLE tr_kkwnodwyk (
    knw_idelemu integer DEFAULT nextval(('tr_kkwnodwyk_s'::text)::regclass) NOT NULL,
    kwe_idelemu integer,
    kwh_idheadu integer,
    ob_idobiektu integer,
    knw_iloscwyk numeric DEFAULT 0,
    knw_iloscbrakow numeric DEFAULT 0,
    knw_datawyk timestamp with time zone,
    knw_flaga integer DEFAULT 0,
    knp_idplanu integer,
    knw_datastart timestamp with time zone,
    knw_tpz numeric DEFAULT 0,
    knw_tpj numeric DEFAULT 0,
    knw_iloscosob numeric DEFAULT 0,
    knw_wydajnosc numeric DEFAULT 0,
    knw_kosztnaj numeric DEFAULT 0,
    knw_kosztnah numeric DEFAULT 0,
    knw_czaswolny numeric DEFAULT 0,
    knw_lp integer,
    knw_tomagmag numeric DEFAULT 0,
    knw_uwagi text,
    zm_idzmiany integer,
    kb_idkubelka integer,
    tsw_idslownika integer DEFAULT 0,
    knw_wspkosztuprac numeric DEFAULT 1,
    mrpp_idpalety_podpieta integer,
    knw_czaswolny_wd numeric DEFAULT 0,
    knw_czaswolny_np numeric DEFAULT 0,
    knw_czaswolny_np_wd numeric DEFAULT 0,
    knw_zaangazpracownika numeric DEFAULT 100,
    knw_iloscskontrolowana numeric DEFAULT 0,
    knw_iloscskontrolowanabraki numeric DEFAULT 0,
    p_idkontrolujacego integer,
    knw_datakontroli timestamp with time zone,
    knw_koopczasreal numeric DEFAULT 0,
    k_idklienta integer,
    knw_zaangazpracwykonanie numeric,
    knw_tomagmagclosed numeric DEFAULT 0 NOT NULL,
    knw_iloscwykrozm numeric[],
    knw_iloscbrakowrozm numeric[],
    knw_iloscopakrozm numeric DEFAULT 0,
    knw_rmp_idsposobu integer DEFAULT 0,
    knw_kwhr_idelemu integer,
    knw_tomagmag_arr numeric[],
    knw_tomagmagclosed_arr numeric[],
    knw_czasefektywny numeric DEFAULT 0
);
