CREATE TABLE tr_kkwnod (
    kwe_idelemu integer DEFAULT nextval(('tr_kkwnod_s'::text)::regclass) NOT NULL,
    kwh_idheadu integer NOT NULL,
    kwe_flaga integer DEFAULT 0,
    the_idelem integer,
    kwe_lp integer NOT NULL,
    kwe_nazwa text,
    the_flaga integer DEFAULT 0,
    top_idoperacji integer,
    the_prbrakow numeric DEFAULT 0,
    kwe_iloscwyk numeric DEFAULT 0,
    kwe_iloscbrakow numeric DEFAULT 0,
    kwe_iloscplanwyk numeric DEFAULT 0,
    kwe_iloscplanbrak numeric DEFAULT 0,
    kwe_tonext numeric DEFAULT 0,
    kwe_tomag numeric DEFAULT 0,
    tjn_idjedn integer,
    kwe_iloscrozplanowana numeric DEFAULT 0,
    ct_idciagu integer,
    kwe_datamin timestamp without time zone DEFAULT '1979-11-29 00:00:00'::timestamp without time zone,
    kwe_datamax timestamp without time zone DEFAULT '2079-11-29 00:00:00'::timestamp without time zone,
    kwe_olp integer,
    kwe_iloscstart numeric DEFAULT 0,
    kwe_iloscplanstart numeric DEFAULT 0,
    kwe_idkooperanta integer,
    kwe_nodtype integer NOT NULL,
    kwe_kosztkooperacji numeric DEFAULT 0,
    kwe_mnoznikwyrobu_l integer DEFAULT 1,
    kwe_mnoznikwyrobu_m integer DEFAULT 1,
    kwe_tomagmag numeric DEFAULT 0,
    kwe_iloscwykprocent numeric DEFAULT 0,
    kwe_iloscrozplanowanaprocent numeric DEFAULT 0,
    kwe_ilosczamuslkoop numeric DEFAULT 0,
    kwe_tpz numeric,
    kwe_tpj numeric,
    kwe_iloscosob numeric,
    kwe_wydajnosc numeric,
    kwe_kosztnaj numeric,
    kwe_kosztnah numeric,
    kwe_wykonanepracrbh numeric DEFAULT 0,
    kwe_czaswolnypracrbh numeric DEFAULT 0,
    kwe_stanowiskoplan integer,
    kwe_opis text,
    the_nextbegin_x numeric,
    kwe_x_licznik numeric,
    kwe_x_mianownik numeric,
    kwe_x_wspc numeric,
    kwe_zaangazpracownika numeric DEFAULT 100,
    kwe_ilosczarejestr numeric DEFAULT 0,
    kwe_ilosczarejestrbraki numeric DEFAULT 0,
    kwe_ilosczarejestrprocent numeric DEFAULT 0,
    kwe_wyk_tjn_idjedn integer,
    kwe_wyk_licznik integer DEFAULT 1,
    kwe_wyk_mianownik integer DEFAULT 1,
    kwe_wyk_dokladnosc integer DEFAULT 0,
    kwe_wspkosztow numeric DEFAULT 0,
    kwe_koopczasreal numeric DEFAULT 0,
    kwe_datazakonczenia timestamp with time zone,
    kwe_datazakonczenia_prev timestamp with time zone,
    kwe_iloscpoprzednikow integer DEFAULT 0,
    spo_idspinacza integer,
    st_idstatusu integer,
    kwe_dataostmod timestamp with time zone DEFAULT now(),
    kwe_tomagmagclosed numeric DEFAULT 0 NOT NULL,
    kwe_iloscwyk_array numeric[],
    kwe_iloscplanwyk_array numeric[]
);
