CREATE TABLE tr_kkwhead (
    kwh_idheadu integer DEFAULT nextval(('tr_kkwhead_s'::text)::regclass) NOT NULL,
    kwh_flaga integer DEFAULT 0,
    zl_idzlecenia integer,
    pz_idplanu integer,
    kwh_datarozp date DEFAULT now(),
    kwh_datazak date DEFAULT now(),
    th_idtechnologii integer,
    kwh_nrkolejny integer DEFAULT 0,
    kwh_numer text,
    kwh_sufixnumeru text,
    p_utworzyl integer,
    ttw_idtowaru integer,
    th_nazwa text,
    th_flaga integer DEFAULT 0,
    kwh_iloscoczek numeric DEFAULT 0,
    kwh_iloscwmag numeric DEFAULT 0,
    tmg_idmagazynu_def integer,
    kwh_prorytet integer,
    thg_idgrupy integer,
    st_idstatusu integer,
    kwh_dataplanstart timestamp without time zone,
    kwh_dataplanstop timestamp without time zone,
    fm_idcentrali integer,
    kwh_datarozwykonania timestamp without time zone,
    kwh_datazakonczeniawyk timestamp with time zone,
    kwh_datazamknieciakkw timestamp with time zone,
    kwh_wykonanepracrbh numeric DEFAULT 0,
    kwh_czaswolnypracrbh numeric DEFAULT 0,
    th_rodzaj integer DEFAULT 1,
    kwh_kolor integer DEFAULT (power((2)::double precision, (24)::double precision) - (1)::double precision),
    kwh_datautworzenia timestamp with time zone DEFAULT now(),
    kwh_opis text,
    kwh_datazakonczenianodow timestamp with time zone,
    th_idkalkulacji integer,
    kwh_iloscwyk numeric DEFAULT 0,
    kwh_iloscwmagclosed numeric DEFAULT 0 NOT NULL,
    kwh_towary integer[],
    kwh_iloscoczek_array numeric[],
    kwh_iloscwyk_array numeric[],
    kwh_rozmiary text[],
    ttw_idxref integer,
    kwh_standomyslne integer,
    kwh_norma_rbh_oczek numeric DEFAULT 0,
    kwh_norma_rbh_wyk numeric DEFAULT 0,
    kwh_norma_mh_oczek numeric DEFAULT 0,
    kwh_norma_mh_wyk numeric DEFAULT 0,
    kwh_wykonanemh numeric DEFAULT 0
);
