CREATE TABLE tr_mrpkalkulacje (
    th_idtechnologii integer NOT NULL,
    kalk_data date DEFAULT now(),
    wl_idwaluty integer DEFAULT 1,
    kalk_przelicznik mpq DEFAULT '1'::mpq,
    tgc_idgrupy integer,
    kalk_narzut_zakup numeric DEFAULT 0,
    kalk_narzut_ogolnozakladowe numeric DEFAULT 0,
    kalk_narzut_stratawbrakach numeric DEFAULT 0,
    kalk_narzut_przerobu numeric DEFAULT 0,
    kalk_narzut_zysku numeric DEFAULT 0,
    kalk_koszt_materialy numeric DEFAULT 0,
    kalk_koszt_robocizna numeric DEFAULT 0,
    kalk_koszt_obrobkaobca numeric DEFAULT 0,
    kalk_koszt_wydzialowe numeric DEFAULT 0,
    kalk_koszt_materialy_podrz numeric DEFAULT 0,
    kalk_koszt_robocizna_podrz numeric DEFAULT 0,
    kalk_koszt_obrobkaobca_podrz numeric DEFAULT 0,
    kalk_koszt_wydzialowe_podrz numeric DEFAULT 0,
    kalk_data_akt_podrz timestamp with time zone,
    kalk_th_idtechnologii integer,
    kalk_sk_idstruktury integer,
    tjn_idjedn integer DEFAULT 1,
    kalk_koszt_narzedzia numeric DEFAULT 0,
    kalk_koszt_inne numeric DEFAULT 0,
    kalk_koszt_narzedzia_podrz numeric DEFAULT 0,
    kalk_koszt_inne_podrz numeric DEFAULT 0
);
