CREATE TABLE tr_pomiary_definicje (
    pd_iddefinicji integer DEFAULT nextval('tr_pomiary_definicje_s'::regclass) NOT NULL,
    pd_nazwa text,
    pd_kod text,
    pd_kolor integer DEFAULT (power((2)::double precision, (24)::double precision) - (1)::double precision),
    pd_opis text,
    pd_czestotliwoscop numeric DEFAULT 0,
    pd_czestotliwoscczas numeric DEFAULT 0,
    th_idtechnologii integer,
    th_rodzaj integer,
    pd_wystepowanie integer DEFAULT 0,
    pd_flaga integer DEFAULT 0,
    ttw_idnarzedzia1 integer,
    ttw_idnarzedzia2 integer,
    sl_idslownika integer,
    pd_typ integer DEFAULT 0,
    pd_numval_min numeric,
    pd_numval_max numeric,
    pd_numval_dokladnosc integer,
    pd_numeric_def numeric,
    es_idelem_def integer,
    pd_int_def integer,
    ob_idobiektu integer,
    the_idelem integer
);
