CREATE TABLE tr_strukturakonstrukcyjna (
    sk_idstruktury integer DEFAULT nextval('tr_strukturakonstrukcyjna_s'::regclass) NOT NULL,
    sk_kod text,
    sk_nazwa text,
    sk_opis text,
    sk_flaga integer DEFAULT 0 NOT NULL,
    ttw_idtowaru integer,
    th_idtechnologii integer,
    fm_idcentrali integer,
    thg_idgrupy integer,
    p_idpracownikazat integer,
    sk_datawpr timestamp without time zone DEFAULT now(),
    sk_dataakceptacji timestamp without time zone,
    sk_dataobowiazywania timestamp without time zone,
    sk_wymiar_x numeric,
    sk_wymiar_y numeric,
    sk_wymiar_z numeric,
    sk_naddatek_x numeric,
    sk_naddatek_y numeric,
    sk_naddatek_z numeric,
    sk_narzut_procent numeric,
    sk_normajakosciowa text,
    sk_cecha1 text,
    sk_cecha2 text,
    sk_cecha3 text,
    sk_operacja1 integer,
    sk_operacja2 integer,
    sk_operacja3 integer,
    sk_operacja4 integer,
    ttw_idmaterialu integer,
    sk_wersjalp integer DEFAULT 1,
    sk_seq integer DEFAULT nextval('tr_strukturakon_wersja'::regclass),
    sk_idzrodla integer,
    sk_wersjatext text,
    sk_idstrukkalksrc integer,
    sk_wymiar_ilosc numeric DEFAULT 0,
    sk_naddatek_ilosc numeric DEFAULT 0
);
