CREATE TABLE tr_technologie (
    th_idtechnologii integer DEFAULT nextval(('tr_technologie_s'::text)::regclass) NOT NULL,
    ttw_idtowaru integer,
    th_kod text,
    th_nazwa text,
    th_flaga integer DEFAULT 0,
    th_optpartia numeric DEFAULT 0,
    thg_idgrupy integer,
    tmg_idmagazynu integer,
    th_mnoznikwyrobu_l integer DEFAULT 1,
    th_mnoznikwyrobu_m integer DEFAULT 1,
    fm_idcentrali integer,
    p_idpraczatwierdz integer,
    st_idstatusu integer,
    th_rodzaj integer DEFAULT 1,
    th_kolor integer DEFAULT (power((2)::double precision, (24)::double precision) - (1)::double precision),
    th_datawpr timestamp without time zone DEFAULT now(),
    th_opis text,
    th_lockby integer,
    th_lockdate timestamp with time zone,
    zl_idzlecenia integer,
    th_numer integer,
    th_sufix text,
    th_kalkulacjasrc integer,
    sk_idstruktury integer
);
