CREATE TABLE ts_miejscamagazynowe (
    mm_idmiejsca integer DEFAULT nextval('ts_miejscamagazynowe_s'::regclass) NOT NULL,
    mm_parent integer,
    mm_l integer,
    mm_r integer,
    mm_kod text,
    mm_fullnumer text,
    mm_flaga integer DEFAULT 0 NOT NULL,
    mm_prorytet integer,
    mm_magazyn integer,
    mm_def_obciazenie numeric DEFAULT 0,
    mm_def_objetosc numeric DEFAULT 0,
    mm_def_cecha1 numeric DEFAULT 0,
    mm_def_cecha2 numeric DEFAULT 0,
    mm_def_cecha3 numeric DEFAULT 0,
    mm_v_obciazenie numeric DEFAULT 0,
    mm_v_objetosc numeric DEFAULT 0,
    mm_v_sumilosc numeric DEFAULT 0,
    tr_idtransfor integer,
    mm_vc_sumilosc numeric DEFAULT 0,
    mm_vc_obciazenie numeric,
    mm_vc_objetosc numeric,
    mm_isleaf boolean NOT NULL,
    mm_lastinwdate timestamp without time zone,
    mm_isactiveforpz boolean DEFAULT true,
    mm_openinwscount smallint DEFAULT 0 NOT NULL,
    zprt_id integer,
    k_ctxidklienta integer,
    fm_idcentrali integer NOT NULL
);
