CREATE TABLE ts_szablonzdarzenia (
    szd_idszablonu integer NOT NULL,
    szd_nazwa text DEFAULT ''::text NOT NULL,
    szd_zdi_id integer,
    szd_tsz_idtypu integer,
    szd_macrozrodlo integer DEFAULT 0 NOT NULL,
    szd_temat text DEFAULT ''::text NOT NULL,
    szd_opis text DEFAULT ''::text NOT NULL,
    szd_typszablonupoczty integer DEFAULT 0 NOT NULL,
    szd_mtpl_id integer,
    szd_flaga integer DEFAULT 0 NOT NULL,
    szd_zdi_idsprawy integer,
    szd_zdp_id integer,
    szd_typklienta integer DEFAULT 0 NOT NULL,
    szd_k_idklienta integer,
    szd_typosoby integer DEFAULT 0 NOT NULL,
    szd_typwlasciciela integer DEFAULT 0 NOT NULL,
    szd_rodzajwlasciciela integer DEFAULT 0 NOT NULL,
    szd_p_idpracownika integer,
    szd_dz_iddzialu integer,
    szd_rol_id integer,
    szd_szl_idstatusu integer,
    szd_typplanowania integer DEFAULT 0 NOT NULL,
    szd_typograniczenia integer DEFAULT 0 NOT NULL,
    szd_typdatyrozpoczecia integer DEFAULT 0 NOT NULL,
    szd_opznieniedatarozp integer DEFAULT 0 NOT NULL,
    szd_typdatyzakonczenia integer DEFAULT 0 NOT NULL,
    szd_opznieniedatazak integer DEFAULT 0 NOT NULL,
    szd_typterminu integer DEFAULT 0 NOT NULL,
    szd_opznienietermin integer DEFAULT 0 NOT NULL,
    szd_old_id integer,
    szd_old_typ text
);
