CREATE TABLE ts_spedycje (
    sp_idspedytora integer DEFAULT nextval(('ts_spedycje_s'::text)::regclass) NOT NULL,
    sp_nazwa text,
    sp_flaga integer DEFAULT 0,
    sp_typ integer DEFAULT 0,
    sp_is_wardostawy character varying(3),
    sp_is_rodzajtransp character varying(1),
    sp_zawartosc text,
    sp_ubezpieczenie numeric,
    sp_usluga integer DEFAULT 1,
    sp_mailpotw text,
    sp_telpotw text,
    sp_n1 text,
    sp_n2 text,
    sp_ubezpieczenie2 numeric DEFAULT 0,
    sp_waganarzut numeric DEFAULT 0,
    sp_mvidklienta integer,
    sp_wagastala numeric DEFAULT 0,
    sp_usluga2 integer DEFAULT 0,
    sp_dodatkoweopcje integer DEFAULT 0,
    sp_urzadnadania integer,
    sp_tytulpobrania text,
    sp_cecha1 text,
    sp_cecha2 text,
    sp_cecha3 text,
    sp_nie_uzywa_opakowan integer DEFAULT 0 NOT NULL,
    sp_domyslne_opakowanie integer,
    sp_wlasciwosc_opakowan integer[],
    sp_wartosc_n1 text,
    sp_wartosc_n2 text
);
