CREATE TABLE tm_numeryseryjne (
    ns_idnumeru integer DEFAULT nextval('tm_numeryseryjne_s'::regclass) NOT NULL,
    fm_idcentrali integer,
    ns_isactive boolean DEFAULT true,
    k_idklienta integer NOT NULL,
    ns_version integer,
    ns_has_abonament integer DEFAULT 0,
    ns_has_produkcja integer DEFAULT 0,
    ns_has_produkcjakkw integer DEFAULT 0,
    ns_has_produkcjamrp integer DEFAULT 0,
    ns_has_turystyka integer DEFAULT 0,
    ns_has_kh integer DEFAULT 0,
    ns_has_logistyka integer DEFAULT 0,
    ns_has_bilety integer DEFAULT 0,
    ns_has_serwis integer DEFAULT 0,
    ns_has_kpir integer DEFAULT 0,
    ns_has_elreceptury integer DEFAULT 0,
    ns_has_swiadectwa integer DEFAULT 0,
    ns_has_kpo integer DEFAULT 0,
    ns_has_kartyrabatowe integer DEFAULT 0,
    ns_licensevalidthru date,
    ns_stanowiskacount integer DEFAULT 0,
    ns_upgradevalidthru date,
    ns_internetcode text,
    ns_has_brakinternetu integer DEFAULT 0,
    ns_mobilestanowiskacount integer DEFAULT 0,
    ns_czytnikstanowiskacount integer DEFAULT 0,
    ns_has_evendoapi integer DEFAULT 0,
    ns_has_projekt integer DEFAULT 0,
    ns_has_serwismrp integer DEFAULT 0,
    ns_has_wms integer DEFAULT 0,
    ns_has_ex_rmsexport integer DEFAULT 0,
    ns_has_ex_invreport integer DEFAULT 0,
    ns_has_ex_towarsync integer DEFAULT 0,
    ns_has_ex_docimport integer DEFAULT 0,
    ns_has_ex_nbpimport integer DEFAULT 0,
    ns_has_ex_salesreport integer DEFAULT 0,
    ns_has_ex_centralatelcrm integer DEFAULT 0,
    ns_has_ex_ekatalog integer DEFAULT 0,
    ns_has_ex_anicareport integer DEFAULT 0,
    ns_has_ex_biswzraport integer DEFAULT 0,
    ns_has_ex_scalaimp integer DEFAULT 0,
    ns_has_ex_calcwynagrodzenia integer DEFAULT 0,
    ns_has_ex_icalendarex integer DEFAULT 0,
    ns_has_ex_dataexport integer DEFAULT 0,
    ns_has_wkh integer DEFAULT 0,
    ns_has_wynajem integer DEFAULT 0,
    ns_has_kgo integer DEFAULT 0,
    ns_has_ex_mlm integer DEFAULT 0,
    ns_has_dvreport integer DEFAULT 0,
    ns_has_loterie integer DEFAULT 0,
    ns_has_crm integer DEFAULT 0,
    ns_istymczasowy boolean DEFAULT false,
    ns_miesiacupgrade date,
    ns_has_kondos integer DEFAULT 0
);
