INSERT INTO kh_wzorceelem VALUES (56, 31, 'Wydanie zewn??trzne', '731', '$(MAGAZYNKTR)', '$(NUMERWLASNY)', '$(KOSZTMAG)', NULL, NULL, 1, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (43, 25, 'Sprzeda?? us??ug', '', '710', '$(NUMERWLASNY)', '$(NETTOBEZZAL)', NULL, NULL, 2, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (42, 25, 'Sprzeda?? towar??w', '', '730', '$(NUMERWLASNY)', '$(NETTOBEZZAL)', NULL, NULL, 1, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (40, 25, 'VAT nale??ny', '', '222-01', '$(NUMERWLASNY)', '$(VATBEZZAL)', NULL, NULL, 0, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (63, 25, 'Sprzeda?? us??ug', '845-$(KLIENT)', '710', '$(NUMERWLASNY)', '$(NETTOZAL)', NULL, NULL, 2, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (64, 25, 'Sprzeda?? towar??w', '845-$(KLIENT)', '730', '$(NUMERWLASNY)', '$(NETTOZAL)', NULL, NULL, 1, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (68, 32, 'Rozrachunki z odbiorcami', '201-$(RRKLIENTKTR)', '', '$(NUMERWLASNY)', '$(RRWARTOSC)', NULL, NULL, 144, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (65, 32, 'VAT nale??ny', '', '222-01', '$(NUMERWLASNY)', '$(VAT)', NULL, NULL, 0, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (69, 32, 'Sprzeda?? us??ug', '', '845-$(KLIENT)', '$(NUMERWLASNY)', '$(NETTO)', NULL, NULL, 0, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (21, 11, 'VAT nale??ny 3%', '', '222-03', '$(NUMERWLASNY)', '$(VAT)', NULL, '3', 0, NULL, NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (22, 11, 'VAT nale??ny 7%', '', '222-07', '$(NUMERWLASNY)', '$(VAT)', NULL, '7', 0, NULL, NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (23, 11, 'VAT nale??ny 22%', '', '222-22', '$(NUMERWLASNY)', '$(VAT)', NULL, '22', 0, NULL, NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (24, 11, 'Sprzeda?? towar??w', '', '730', '$(NUMERWLASNY)', '$(NETTO)', NULL, NULL, 1, NULL, NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (25, 11, 'Sprzeda?? us??ug', '', '710', '$(NUMERWLASNY)', '$(NETTO)', NULL, NULL, 2, NULL, NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (26, 11, 'Nale??no??ci', '201-$(KLIENT)', '', '$(NUMERWLASNY)', '$(BRUTTO)', NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (27, 13, 'Wyp??ata', '202-$(KASABANKKTR)', '$(KASABANKKTR)', '$(OPIS)', '$(WARTOSC)', NULL, NULL, 16, NULL, NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (28, 13, 'Wp??ata', '$(KASABANKKTR)', '201-$(KLIENTKTR)', '$(OPIS)', '$(WARTOSC)', NULL, NULL, 8, NULL, NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (29, 15, 'Magazyn', '$(MAGAZYNKTR)', '300-$(KLIENT)', '$(NUMERWLASNY)', '$(KOSZTNAB)', NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (30, 17, 'Rozlicznie zakupu', '300-$(KLIENT)', '', '$(NUMERDOK)', '$(NETTO)', NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (31, 17, 'VAT naliczony', '221', '', '$(NUMERDOK)', '$(VAT)', NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (32, 17, 'Zobowi??zanie', '', '202-$(KLIENTKTR)', '$(NUMERDOK)', '$(BRUTTO)', NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (33, 19, 'Zobowi??zanie', '', '202-$(KLIENTKTR)', '$(NUMERDOK)', '$(BRUTTO)', NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (34, 19, 'Koszt', '$(TOWARKT2)', '490', '$(NUMERDOK) - $(NAZWAEL)', '$(NETTO)', NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (35, 19, 'Koszt', '$(TOWARKT1)', '', '$(NUMERDOK) - $(NAZWAEL)', '$(NETTO)', NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (36, 19, 'VAT naliczony', '221', '', '$(NUMERDOK)', '$(VAT)', NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (37, 21, 'Przesuni??cia MM', '$(MAGAZYNKTR)', '$(MAGAZYNSRCKTR)', '$(NUMERWLASNY)', '$(KOSZTNAB)', NULL, NULL, 1, NULL, NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (38, 23, 'Wydanie zewn??trzne', '731', '$(MAGAZYNKTR)', '$(NUMERWLASNY)', '$(KOSZTMAG)', NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (71, 33, 'Wyp??ata', '202-$(KLIENTKTR)', '$(KASABANKKTR)', '$(OPIS)', '$(WARTOSC)', NULL, NULL, 1040, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (72, 33, 'Wp??ata', '$(KASABANKKTR)', '201-$(KLIENTKTR)', '$(OPIS)', '$(WARTOSC)', NULL, NULL, 1032, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (73, 33, 'Wyp??ata', '202-$(KLIENTKTR)', '$(KASABANKKTR)', '$(OPIS)', '$(RRWARTOSC)', NULL, NULL, 144, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (47, 27, 'Magazyn', '$(MAGAZYNKTR)', '300-$(KLIENT)', '$(NUMERWLASNY)', '$(KOSZTNAB)', NULL, NULL, 0, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (48, 28, 'Rozlicznie zakupu', '300-$(KLIENT)', '', '$(NUMERDOK); $(NUMERWLASNY)', '$(NETTO)', NULL, NULL, 0, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (49, 28, 'VAT naliczony', '221-01', '', '$(NUMERDOK); $(NUMERWLASNY)', '$(VAT)', NULL, NULL, 0, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (74, 33, 'Wp??ata', '$(KASABANKKTR)', '201-$(KLIENTKTR)', '$(OPIS)', '$(RRWARTOSC)', NULL, NULL, 136, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (46, 26, 'Wp??ata', '$(KASABANKKTR)', '202-$(KLIENTKTR)', '$(OPIS)', '$(WARTOSC)', NULL, NULL, 1032, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (53, 29, 'Koszt', '$(TOWARKT1)', '', '$(NUMERDOK); $(NUMERWLASNY); $(NAZWAEL)', '$(BRUTTO)', NULL, NULL, 0, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (54, 29, 'VAT naliczony', '221-01', '', '$(NUMERDOK); $(NUMERWLASNY)', '$(VAT)', NULL, NULL, 0, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (55, 30, 'Przesuni??cia MM', '$(MAGAZYNKTR)', '$(MAGAZYNSRCKTR)', '$(NUMERWLASNY)', '$(KOSZTNAB)', NULL, NULL, 1, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (45, 26, 'Wyp??ata', '201-$(KLIENTKTR)', '$(KASABANKKTR)', '$(OPIS)', '$(WARTOSC)', NULL, NULL, 1040, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (57, 25, 'Rozrachunki z odbiorcami', '201-$(RRKLIENTKTR)', '', '$(NUMERWLASNY)', '$(RRWARTOSC)', NULL, NULL, 144, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (61, 26, 'Wp??ata', '$(KASABANKKTR)', '202-$(KLIENTKTR)', '$(OPIS)', '$(RRWARTOSC)', NULL, NULL, 136, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (60, 26, 'Wyp??ata', '201-$(KLIENTKTR)', '$(KASABANKKTR)', '$(OPIS)', '$(RRWARTOSC)', NULL, NULL, 144, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (58, 29, 'Rozrachunki z dostawcami', '', '202-$(RRKLIENTKTR)', '$(NUMERDOK); $(NUMERWLASNY)', '$(RRWARTOSC)', NULL, NULL, 136, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (59, 29, 'Koszt', '$(TOWARKT1)', '', '$(NUMERDOK); $(NUMERWLASNY); $(NAZWAEL)', '$(NETTO)', NULL, NULL, 0, '', NULL, 0, NULL);
INSERT INTO kh_wzorceelem VALUES (62, 28, 'Rozrachunki z dostawcami', '', '202-$(RRKLIENTKTR)', '$(NUMERDOK); $(NUMERWLASNY)', '$(RRWARTOSC)', NULL, NULL, 136, '', NULL, 0, NULL);
