INSERT INTO tg_jednostki VALUES (4, 'Us??uga', 'us??', 0, NULL, 0, NULL);
INSERT INTO tg_jednostki VALUES (5, 'Kilometr', 'km', 0, NULL, 0, NULL);
INSERT INTO tg_jednostki VALUES (6, 'Metr', 'm', 0, NULL, 0, NULL);
INSERT INTO tg_jednostki VALUES (7, 'Roboczogodzina', 'rbh', 0, NULL, 0, NULL);
INSERT INTO tg_jednostki VALUES (8, 'Operacja', 'oper', 1, NULL, 0, NULL);
INSERT INTO tg_jednostki VALUES (9, 'sztuka wyrobu', 'szt wyr', 1, NULL, 0, NULL);
INSERT INTO tg_jednostki VALUES (10, 'Tona', 't.', 0, '', 0, NULL);
INSERT INTO tg_jednostki VALUES (11, 'Jednostka miary', 'j.m.', 2, '', 0, NULL);
INSERT INTO tg_jednostki VALUES (3, 'Kilogram', 'kg', 0, '', 0, NULL);
INSERT INTO tg_jednostki VALUES (1, 'Sztuka', 'szt', 0, '', 0, NULL);
INSERT INTO tg_jednostki VALUES (12, 'm2', 'm2', 0, '', 0, NULL);
