INSERT INTO tg_partie VALUES (1, 2, NULL, NULL, NULL, NULL, NULL, -2, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 1, NULL, NULL, 0);
INSERT INTO tg_partie VALUES (2, 8, NULL, NULL, NULL, NULL, NULL, -2, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 2, NULL, NULL, 0);
INSERT INTO tg_partie VALUES (4, 8, NULL, NULL, NULL, NULL, NULL, 1, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 2, NULL, NULL, 0);
INSERT INTO tg_partie VALUES (3, 2, NULL, NULL, NULL, NULL, NULL, 1, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 1, NULL, NULL, 0);
