INSERT INTO ts_exsystems VALUES (12, 'Praca podstawowa', 'NORMAL', 0);
INSERT INTO ts_exsystems VALUES (6, 'Mobilne Vendo', 'MOBILE', 0);
INSERT INTO ts_exsystems VALUES (3, 'Roner', 'RONER', 0);
INSERT INTO ts_exsystems VALUES (5, 'Firma-Firma', 'FIRMAFIRMA', 0);
INSERT INTO ts_exsystems VALUES (7, 'eKatalog', 'EKATALOG', 0);
INSERT INTO ts_exsystems VALUES (13, 'Sote sklep', 'SOTE', 0);
INSERT INTO ts_exsystems VALUES (14, 'Allegro', 'ALLEGRO', 0);
INSERT INTO ts_exsystems VALUES (15, 'Inne', 'INNE', 0);
INSERT INTO ts_exsystems VALUES (16, 'PS Mobile', 'PSMOBILE', 0);
INSERT INTO ts_exsystems VALUES (19, 'PgmSoft', 'PGMSOFT', 0);
INSERT INTO ts_exsystems VALUES (9, 'EWD', 'EWD', 0);
INSERT INTO ts_exsystems VALUES (20, 'XML CFI', 'XMLCFI', 0);
INSERT INTO ts_exsystems VALUES (18, 'MLM', 'MLM', 0);
INSERT INTO ts_exsystems VALUES (23, 'Adept', 'ADEPT', 0);
INSERT INTO ts_exsystems VALUES (24, 'Kolektor danych', 'KOLEKTOR', 0);
INSERT INTO ts_exsystems VALUES (25, 'Shoper', 'SHOPER', 0);
INSERT INTO ts_exsystems VALUES (26, 'eBay', 'EBAY', 0);
INSERT INTO ts_exsystems VALUES (27, 'Zoio', 'ZOIO', 1);
INSERT INTO ts_exsystems VALUES (28, 'Sosimply', 'SOSIMPLY', 1);
INSERT INTO ts_exsystems VALUES (29, 'BaseLinker', 'BASELINKER', 1);
INSERT INTO ts_exsystems VALUES (4, 'B2B eVendo', 'EVENDO', 0);
