INSERT INTO ts_powiaty VALUES (5, 'Austria', 'AT', 2, 3);
INSERT INTO ts_powiaty VALUES (6, 'Belgia', 'BE', 2, 3);
INSERT INTO ts_powiaty VALUES (7, 'Dania', 'DK', 2, 3);
INSERT INTO ts_powiaty VALUES (8, 'Finlandia', 'FI', 2, 3);
INSERT INTO ts_powiaty VALUES (9, 'Francja', 'FR', 2, 3);
INSERT INTO ts_powiaty VALUES (10, 'Grecja', 'EL', 2, 3);
INSERT INTO ts_powiaty VALUES (11, 'Hiszpania', 'ES', 2, 3);
INSERT INTO ts_powiaty VALUES (12, 'Holandia', 'NL', 2, 3);
INSERT INTO ts_powiaty VALUES (13, 'Irlandia', 'IE', 2, 3);
INSERT INTO ts_powiaty VALUES (14, 'Luksemburg', 'LU', 2, 3);
INSERT INTO ts_powiaty VALUES (15, 'Niemcy', 'DE', 2, 3);
INSERT INTO ts_powiaty VALUES (16, 'Portugalia', 'PT', 2, 3);
INSERT INTO ts_powiaty VALUES (17, 'Szwecja', 'SE', 2, 3);
INSERT INTO ts_powiaty VALUES (18, 'Wielka Brytania', 'GB', 2, 3);
INSERT INTO ts_powiaty VALUES (19, 'W??ochy', 'IT', 2, 3);
INSERT INTO ts_powiaty VALUES (20, 'Cypr', 'CY', 2, 3);
INSERT INTO ts_powiaty VALUES (21, 'Czechy', 'CZ', 2, 3);
INSERT INTO ts_powiaty VALUES (22, 'Estonia', 'EE', 2, 3);
INSERT INTO ts_powiaty VALUES (23, 'Litwa', 'LT', 2, 3);
INSERT INTO ts_powiaty VALUES (24, '??otwa', 'LV', 2, 3);
INSERT INTO ts_powiaty VALUES (25, 'Malta', 'MT', 2, 3);
INSERT INTO ts_powiaty VALUES (26, 'S??owacja', 'SK', 2, 3);
INSERT INTO ts_powiaty VALUES (27, 'S??owenia', 'SI', 2, 3);
INSERT INTO ts_powiaty VALUES (28, 'W??gry', 'HU', 2, 3);
INSERT INTO ts_powiaty VALUES (29, 'Albania', 'AL', 0, 2);
INSERT INTO ts_powiaty VALUES (30, 'Bo??nia-Hercegowina', 'BA', 0, 2);
INSERT INTO ts_powiaty VALUES (31, 'Turcja', 'TR', 0, 2);
INSERT INTO ts_powiaty VALUES (32, 'Ukraina', 'UA', 0, 2);
INSERT INTO ts_powiaty VALUES (33, 'Jugos??awia', 'YU', 0, 2);
INSERT INTO ts_powiaty VALUES (34, 'Bu??garia', 'BG', 2, 3);
INSERT INTO ts_powiaty VALUES (35, 'Bia??oru??', 'BY', 0, 2);
INSERT INTO ts_powiaty VALUES (36, 'Szwajcaria', 'CH', 0, 2);
INSERT INTO ts_powiaty VALUES (38, 'Islandia', 'IS', 0, 2);
INSERT INTO ts_powiaty VALUES (39, 'Liechtenstein', 'LI', 0, 2);
INSERT INTO ts_powiaty VALUES (40, 'Mo??dawia', 'MD', 0, 2);
INSERT INTO ts_powiaty VALUES (41, 'Republika Macedonii', 'MK', 0, 2);
INSERT INTO ts_powiaty VALUES (42, 'Norwegia', 'NO', 0, 2);
INSERT INTO ts_powiaty VALUES (43, 'Rumunia', 'RO', 2, 3);
INSERT INTO ts_powiaty VALUES (44, 'Federacja Rosyjska', 'RU', 0, 2);
INSERT INTO ts_powiaty VALUES (45, 'Stany Zjednoczone Ameryki', 'US', 0, 2);
INSERT INTO ts_powiaty VALUES (46, 'Japonia', 'JP', 0, 2);
INSERT INTO ts_powiaty VALUES (49, 'Indie', 'IN', 0, 2);
INSERT INTO ts_powiaty VALUES (48, 'Meksyk', 'MX', 0, 2);
INSERT INTO ts_powiaty VALUES (50, 'Brazylia', 'BR', 0, 2);
INSERT INTO ts_powiaty VALUES (51, 'Wenezuela', 'WN', 0, 2);
INSERT INTO ts_powiaty VALUES (52, 'Tunezja', 'TN', 0, 2);
INSERT INTO ts_powiaty VALUES (53, 'Singapur', 'SG', 0, 2);
INSERT INTO ts_powiaty VALUES (54, 'Republika Po??udniowej Afryki', 'SA', 0, 2);
INSERT INTO ts_powiaty VALUES (55, 'Nowa Zelandia', 'NZ', 0, 2);
INSERT INTO ts_powiaty VALUES (56, 'Kenia', 'KN', 0, 2);
INSERT INTO ts_powiaty VALUES (57, 'Izrael', 'IL', 0, 2);
INSERT INTO ts_powiaty VALUES (58, 'Chiny', 'CN', 0, 2);
INSERT INTO ts_powiaty VALUES (59, 'Australia', 'AU', 0, 2);
INSERT INTO ts_powiaty VALUES (60, 'Argentyna', 'AG', 0, 2);
INSERT INTO ts_powiaty VALUES (61, 'Korea Po??udniowa', 'KS', 0, 2);
INSERT INTO ts_powiaty VALUES (3, 'Polska', 'PL', 7, 1);
INSERT INTO ts_powiaty VALUES (37, 'Chorwacja', 'HR', 2, 2);
INSERT INTO ts_powiaty VALUES (47, 'Kanada', 'CA', 0, 2);
INSERT INTO ts_powiaty VALUES (0, 'Inne', 'OT', 0, 2);
