INSERT INTO tm_rodzajeinfo VALUES (1, 'FV', 'Faktura VAT');
INSERT INTO tm_rodzajeinfo VALUES (11, 'KFV', 'Faktura VAT - korekta');
INSERT INTO tm_rodzajeinfo VALUES (21, 'FVZ', 'Faktura VAT - korekta zbiorcza');
INSERT INTO tm_rodzajeinfo VALUES (103, 'ZA', 'Faktura Zaliczkowa');
INSERT INTO tm_rodzajeinfo VALUES (113, 'KZA', 'Faktura Zaliczkowa - korekta');
INSERT INTO tm_rodzajeinfo VALUES (123, 'ZR', 'Rozliczenie zaliczek');
INSERT INTO tm_rodzajeinfo VALUES (237, 'KPP', 'Faktura Poparagonowa - korekta');
INSERT INTO tm_rodzajeinfo VALUES (7, 'PR', 'Paragon Fiskalny');
INSERT INTO tm_rodzajeinfo VALUES (77, 'WR', 'WZR');
INSERT INTO tm_rodzajeinfo VALUES (17, 'KPR', 'Paragon Fiskalny - korekta');
INSERT INTO tm_rodzajeinfo VALUES (3, 'PF', 'Faktura ProForma');
INSERT INTO tm_rodzajeinfo VALUES (30, 'ZO', 'Przyj??cie Zam??wienia');
INSERT INTO tm_rodzajeinfo VALUES (34, 'OF', 'Oferta');
INSERT INTO tm_rodzajeinfo VALUES (9, 'SW', 'Sprzeda?? Wewn??trzna');
INSERT INTO tm_rodzajeinfo VALUES (19, 'KSW', 'Sprzeda?? Wewn??trzna - korekta');
INSERT INTO tm_rodzajeinfo VALUES (116, 'FW', 'Faktura Wewn??trzna');
INSERT INTO tm_rodzajeinfo VALUES (126, 'KFW', 'Faktura wewn??trzna - korekta');
INSERT INTO tm_rodzajeinfo VALUES (101, 'IS', 'Inna Sprzeda??');
INSERT INTO tm_rodzajeinfo VALUES (201, 'KIS', 'Inna Sprzeda?? - korekta');
INSERT INTO tm_rodzajeinfo VALUES (117, 'ISR', 'Inna Sprzeda?? Rozrachunek');
INSERT INTO tm_rodzajeinfo VALUES (217, 'KISR', 'Inna Sprzeda?? Rozrachunek - korekta');
INSERT INTO tm_rodzajeinfo VALUES (102, 'FI', 'Faktura-Invoice');
INSERT INTO tm_rodzajeinfo VALUES (202, 'KFI', 'Faktura-Invoice - korekta');
INSERT INTO tm_rodzajeinfo VALUES (37, 'PP', 'Faktura Poparagonowa');
INSERT INTO tm_rodzajeinfo VALUES (35, 'PS', 'Plan Sprzeda??y');
INSERT INTO tm_rodzajeinfo VALUES (114, 'NO', 'Nota Obci????eniowa');
INSERT INTO tm_rodzajeinfo VALUES (251, 'AW', 'Awizo Wydania');
INSERT INTO tm_rodzajeinfo VALUES (252, 'DP', 'Dokument Prefabrykacji');
INSERT INTO tm_rodzajeinfo VALUES (253, 'NM-', 'Nota Mi??dzyoddzia??owa -');
INSERT INTO tm_rodzajeinfo VALUES (254, 'NM+', 'Nota Mi??dzyoddzia??owa +');
INSERT INTO tm_rodzajeinfo VALUES (256, 'ZK', 'Zapytanie od kupujacego');
INSERT INTO tm_rodzajeinfo VALUES (145, 'FZ', 'Faktura Zakupowa');
INSERT INTO tm_rodzajeinfo VALUES (345, 'KFZ', 'Faktura Zakupu - korekta');
INSERT INTO tm_rodzajeinfo VALUES (246, 'ZZ', 'Faktura Zaliczkowa Zakupu');
INSERT INTO tm_rodzajeinfo VALUES (247, 'KZZ', 'Faktura Zaliczkowa Zakupu - korekta');
INSERT INTO tm_rodzajeinfo VALUES (110, 'RR', 'Faktura VAT RR');
INSERT INTO tm_rodzajeinfo VALUES (210, 'KRR', 'Faktura VAT RR - korekta');
INSERT INTO tm_rodzajeinfo VALUES (250, 'AP', 'Awizo Przyj??cia');
INSERT INTO tm_rodzajeinfo VALUES (100, 'RZ', 'Rachunek Zakupu');
INSERT INTO tm_rodzajeinfo VALUES (200, 'KRZ', 'Rachunek Zakupu - korekta');
INSERT INTO tm_rodzajeinfo VALUES (45, 'RWK', 'Koszty');
INSERT INTO tm_rodzajeinfo VALUES (245, 'KKO', 'Koszty - korekta');
INSERT INTO tm_rodzajeinfo VALUES (31, 'ZW', 'Zam??wienie');
INSERT INTO tm_rodzajeinfo VALUES (105, 'ZP', 'Zapytanie Ofertowe');
INSERT INTO tm_rodzajeinfo VALUES (115, 'NK', 'Nota Obci????eniowa - koszt');
INSERT INTO tm_rodzajeinfo VALUES (118, 'IZ', 'Inny Zakup');
INSERT INTO tm_rodzajeinfo VALUES (218, 'KIZ', 'Inny Zakup - korekta');
INSERT INTO tm_rodzajeinfo VALUES (119, 'IZR', 'Inny Zakup Rozrachunek');
INSERT INTO tm_rodzajeinfo VALUES (219, 'KIZR', 'Inny Zakup Rozrachunek - korekta');
INSERT INTO tm_rodzajeinfo VALUES (255, 'ZT', 'Zapotrzebowanie');
INSERT INTO tm_rodzajeinfo VALUES (257, 'OD', 'Oferta od dostawcy');
INSERT INTO tm_rodzajeinfo VALUES (2, 'WZ', 'Wydanie Zewn??trzne');
INSERT INTO tm_rodzajeinfo VALUES (12, 'KWZ', 'Wydanie Zewn??trzne - korekta');
INSERT INTO tm_rodzajeinfo VALUES (0, 'PZ', 'Przyj??cie Zewn??trzne');
INSERT INTO tm_rodzajeinfo VALUES (10, 'KPZ', 'Przyj??cie Zewn??trzne - korekta');
INSERT INTO tm_rodzajeinfo VALUES (4, 'RW', 'Rozch??d Wewn??trzny');
INSERT INTO tm_rodzajeinfo VALUES (14, 'KRW', 'Rozch??d Wewn??trzny - korekta');
INSERT INTO tm_rodzajeinfo VALUES (5, 'PW', 'Przych??d Wewn??trzny');
INSERT INTO tm_rodzajeinfo VALUES (15, 'KPW', 'Przych??d Wewn??trzny - korekta');
INSERT INTO tm_rodzajeinfo VALUES (6, 'MM-', 'Przesuni??cie Mi??dzymagazynowe -');
INSERT INTO tm_rodzajeinfo VALUES (8, 'MM+', 'Przesuni??cie Mi??dzymagazynowe +');
INSERT INTO tm_rodzajeinfo VALUES (61, 'ZWP', 'Zwrot Z Produkcji');
INSERT INTO tm_rodzajeinfo VALUES (104, 'TK', 'Dokument TK');
INSERT INTO tm_rodzajeinfo VALUES (249, 'WP', 'Wypo??yczenie');
INSERT INTO tm_rodzajeinfo VALUES (260, 'WP-', 'Wypo??yczalnia -');
INSERT INTO tm_rodzajeinfo VALUES (261, 'WP+', 'Wypo??yczalnia +');
INSERT INTO tm_rodzajeinfo VALUES (33, 'RE-', 'Zam??wienie Wewn??trzne-');
INSERT INTO tm_rodzajeinfo VALUES (43, 'RE+', 'Zam??wienie Wewn??trzne+');
INSERT INTO tm_rodzajeinfo VALUES (108, 'WK', 'Wydanie Do Kontrahenta');
INSERT INTO tm_rodzajeinfo VALUES (109, 'PK', 'Przyj??cie Od Kontrahenta');
INSERT INTO tm_rodzajeinfo VALUES (208, 'KWK', 'Wydanie Do Kontrahenta - korekta');
INSERT INTO tm_rodzajeinfo VALUES (209, 'KPK', 'Przyj??cie Od Kontrahenta - korekta');
INSERT INTO tm_rodzajeinfo VALUES (111, 'RP', 'Przyj??cie od rolnika');
INSERT INTO tm_rodzajeinfo VALUES (211, 'KRP', 'Przyj??cie od rolnika - korekta');
INSERT INTO tm_rodzajeinfo VALUES (36, 'SM', 'Specyfikacja Materia??owa');
INSERT INTO tm_rodzajeinfo VALUES (70, 'KS', 'Konsygnata');
INSERT INTO tm_rodzajeinfo VALUES (71, 'ZKS', 'Zwrot konsygnaty');
INSERT INTO tm_rodzajeinfo VALUES (72, 'ZKP', 'Zwrot Konsygnaty Plus');
INSERT INTO tm_rodzajeinfo VALUES (73, 'ZKM', 'Zwrot Konsygnaty Minus');
INSERT INTO tm_rodzajeinfo VALUES (400, 'WM', 'Przesuni??cie WMS');
INSERT INTO tm_rodzajeinfo VALUES (410, 'WMI', 'Przesuni??cie WMSI');
INSERT INTO tm_rodzajeinfo VALUES (401, 'PE', 'Przepartiowanie');
INSERT INTO tm_rodzajeinfo VALUES (403, 'KJ', 'Kontrola jako??ci');
INSERT INTO tm_rodzajeinfo VALUES (402, 'PC', 'Przeszacowanie');
INSERT INTO tm_rodzajeinfo VALUES (404, 'EK', 'Przepakowanie');
INSERT INTO tm_rodzajeinfo VALUES (107, 'ZB', 'Zobowi??zanie');
INSERT INTO tm_rodzajeinfo VALUES (106, 'NL', 'Nale??no????');
INSERT INTO tm_rodzajeinfo VALUES (32, 'ZEP', 'Zestawienie Produkcji');
INSERT INTO tm_rodzajeinfo VALUES (46, 'INW', 'Inwentaryzacja');
INSERT INTO tm_rodzajeinfo VALUES (47, 'IWM', 'Inwentaryzacja WMS');
INSERT INTO tm_rodzajeinfo VALUES (300, 'GKFV', 'Generator Korekt Faktur VAT');
INSERT INTO tm_rodzajeinfo VALUES (411, 'PD', 'Protok???? Dostawy');
INSERT INTO tm_rodzajeinfo VALUES (501, 'FK', 'Faktura Zakupowa');
INSERT INTO tm_rodzajeinfo VALUES (511, 'KOO', 'Faktura Zakupu - korekta');
INSERT INTO tm_rodzajeinfo VALUES (502, 'WO', 'Wydanie Odpad??w');
INSERT INTO tm_rodzajeinfo VALUES (512, 'KWO', 'Wydanie Odpad??w - korekta');
INSERT INTO tm_rodzajeinfo VALUES (545, 'FO', 'Faktura VAT');
INSERT INTO tm_rodzajeinfo VALUES (565, 'KFO', 'Faktura VAT - korekta');
INSERT INTO tm_rodzajeinfo VALUES (500, 'PO', 'Przyj??cie Odpad??w');
INSERT INTO tm_rodzajeinfo VALUES (510, 'KPO', 'Przyj??cie Odpad??w - korekta');
