CREATE OR REPLACE FUNCTION 
    LANGUAGE sql
    AS $_$
 SELECT vendo.setTParamI('GM.ALLOWPARTIALPARTIA'||COALESCE($1::text,''),vendo.getTParamI('GM.ALLOWPARTIALPARTIA'||COALESCE($1::text,''),0)+$2);
$_$;
