CREATE OR REPLACE FUNCTION 
    LANGUAGE sql IMMUTABLE
    AS $_$
SELECT (CASE WHEN $2>=$3 AND $2<=$4 THEN $1 ELSE 0 END)
$_$;


--
--

CREATE OR REPLACE FUNCTION 
    LANGUAGE sql IMMUTABLE
    AS $_$
SELECT (CASE WHEN $2>=$3 AND $2<=$4 THEN $1 ELSE 0 END)
$_$;
